In [302]:
%pip install duckdb

Requirement already satisfied: duckdb in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.5.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [303]:
import duckdb
import pandas as pd

con = duckdb.connect("../data/shelterflow.duckdb")
intakes = con.execute("SELECT * FROM bronze_intakes").df()
outcomes = con.execute("SELECT * FROM bronze_outcomes").df()

# Exploratory Data Analysis of Shelter Intakes & Outcomes

## Intakes
### Column Info

In [304]:
intakes.info()

<class 'pandas.DataFrame'>
RangeIndex: 80187 entries, 0 to 80186
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age_upon_intake   80187 non-null  str
 1   animal_id         80187 non-null  str
 2   animal_type       80187 non-null  str
 3   breed             80187 non-null  str
 4   color             80187 non-null  str
 5   datetime          80187 non-null  str
 6   datetime2         80187 non-null  str
 7   found_location    80187 non-null  str
 8   intake_condition  80187 non-null  str
 9   intake_type       80187 non-null  str
 10  name              55603 non-null  str
 11  sex_upon_intake   80186 non-null  str
dtypes: str(12)
memory usage: 7.3 MB

### Descriptive Statistics

In [305]:
intakes.describe()

,age_upon_intake,animal_id,animal_type,breed,color,datetime,datetime2,found_location,intake_condition,intake_type,name,sex_upon_intake
count,80187,80187,80187,80187,80187,80187,80187,80187,80187,80187,55603,80186
unique,46,72365,5,2166,529,57055,57055,36772,8,5,14731,5
top,1 year,A721033,Dog,Domestic Shorthair Mix,Black/White,2016-09-23T12:00:00.000,2016-09-23T12:00:00.000,Austin (TX),Normal,Stray,Bella,Intact Male
freq,14672,13,45743,23519,8340,64,64,14443,70520,56280,357,25488

### Missing Values

In [306]:
intakes.isnull().sum()

age_upon_intake         0
animal_id               0
animal_type             0
breed                   0
color                   0
datetime                0
datetime2               0
found_location          0
intake_condition        0
intake_type             0
name                24584
sex_upon_intake         1
dtype: int64

### Duplicate Rows

In [307]:
intakes.duplicated().sum()

26

### <a id="intakes-breeds"></a>Breed Distribution

In [308]:
intakes["breed"].value_counts()

breed
Domestic Shorthair Mix              23519
Pit Bull Mix                         6382
Chihuahua Shorthair Mix              4860
Labrador Retriever Mix               4841
Domestic Medium Hair Mix             2337
                                    ...
Siamese/Snowshoe                        1
Yorkshire Terrier/Dachshund             1
Guinea                                  1
Norfolk Terrier/Pug                     1
Australian Shepherd/Basset Hound        1
Name: count, Length: 2166, dtype: int64

### Intake Type Distribution

In [309]:
intakes["intake_type"].value_counts()

intake_type
Stray                 56280
Owner Surrender       15156
Public Assist          5033
Wildlife               3467
Euthanasia Request      251
Name: count, dtype: int64

### Animal Type Distribution

In [310]:
intakes["animal_type"].value_counts()

animal_type
Dog          45743
Cat          29659
Other         4434
Bird           342
Livestock        9
Name: count, dtype: int64

### Top 50 Dog Breeds

In [311]:
intakes[intakes["animal_type"] == "Dog"]["breed"].value_counts().head(50)

breed
Pit Bull Mix                          6382
Chihuahua Shorthair Mix               4860
Labrador Retriever Mix                4841
German Shepherd Mix                   1963
Australian Cattle Dog Mix             1105
Dachshund Mix                          813
Boxer Mix                              689
Border Collie Mix                      667
Miniature Poodle Mix                   662
Catahoula Mix                          484
Australian Shepherd Mix                470
Rat Terrier Mix                        469
Yorkshire Terrier Mix                  449
Siberian Husky Mix                     442
Jack Russell Terrier Mix               437
Miniature Schnauzer Mix                404
Beagle Mix                             394
Staffordshire Mix                      385
Chihuahua Longhair Mix                 371
Great Pyrenees Mix                     350
Cairn Terrier Mix                      350
Pointer Mix                            338
Rottweiler Mix                         327
American Bulldog Mix                   325
Shih Tzu Mix                           292
Plott Hound Mix                        255
Anatol Shepherd Mix                    255
Chihuahua Shorthair/Dachshund          252
Black Mouth Cur Mix                    248
Australian Kelpie Mix                  243
Labrador Retriever                     241
German Shepherd                        236
Pit Bull                               234
American Staffordshire Terrier Mix     219
Labrador Retriever/Pit Bull            218
Chihuahua Shorthair                    204
American Pit Bull Terrier Mix          182
Dachshund/Chihuahua Shorthair          179
German Shepherd/Labrador Retriever     160
Golden Retriever Mix                   157
Miniature Pinscher Mix                 156
Maltese Mix                            155
Queensland Heeler Mix                  150
Chow Chow Mix                          146
Labrador Retriever/German Shepherd     140
Basset Hound Mix                       127
Border Terrier Mix                     126
Pug Mix                                125
Doberman Pinsch Mix                    124
Pomeranian Mix                         123
Name: count, dtype: int64

### Count of Unique Dog Breeds

In [312]:
intakes[intakes["animal_type"] == "Dog"]["breed"].nunique()

1925

In [313]:
pd.set_option("display.max_rows", None)

### Pit Bull Breed Variations

In [314]:
intakes[intakes["breed"].str.contains("pit bull", case=False, na=False)]["breed"].value_counts()

breed
Pit Bull Mix                                           6382
Pit Bull                                                234
Labrador Retriever/Pit Bull                             218
American Pit Bull Terrier Mix                           182
Pit Bull/Labrador Retriever                             107
Pit Bull/Boxer                                           53
Boxer/Pit Bull                                           49
Pit Bull/Australian Cattle Dog                           29
Pit Bull/Catahoula                                       28
American Bulldog/Pit Bull                                19
Pit Bull/Chinese Sharpei                                 18
Australian Cattle Dog/Pit Bull                           18
Pit Bull/Pointer                                         18
German Shepherd/Pit Bull                                 16
Pit Bull/Chihuahua Shorthair                             12
Pit Bull/German Shepherd                                 11
Pointer/Pit Bull                                         11
Catahoula/Pit Bull                                       11
Pit Bull/Basset Hound                                     9
American Pit Bull Terrier                                 9
Dachshund/Pit Bull                                        8
Chow Chow/Pit Bull                                        7
Blue Lacy/Pit Bull                                        7
Pit Bull/Weimaraner                                       7
Australian Kelpie/Pit Bull                                7
Pit Bull/Bulldog                                          7
Chihuahua Shorthair/Pit Bull                              7
Pit Bull/Dachshund                                        6
Black Mouth Cur/Pit Bull                                  6
Pit Bull/Plott Hound                                      5
Basset Hound/Pit Bull                                     5
Pit Bull/Dalmatian                                        5
Queensland Heeler/Pit Bull                                5
Jack Russell Terrier/Pit Bull                             5
Pit Bull/Blue Lacy                                        5
Irish Setter/Pit Bull                                     5
Pit Bull/Boston Terrier                                   5
Siberian Husky/Pit Bull                                   4
Pit Bull/Chow Chow                                        4
Pit Bull/Alaskan Husky                                    4
Pit Bull/Rottweiler                                       4
Carolina Dog/Pit Bull                                     4
Weimaraner/Pit Bull                                       4
Pointer/American Pit Bull Terrier                         4
Pit Bull/Mastiff                                          4
Plott Hound/Pit Bull                                      4
Flat Coat Retriever/Pit Bull                              3
Pit Bull/Black Mouth Cur                                  3
Doberman Pinsch/Pit Bull                                  3
Great Dane/Pit Bull                                       3
Chinese Sharpei/Pit Bull                                  3
Pit Bull/Rhod Ridgeback                                   3
Mastiff/Pit Bull                                          3
Border Collie/Pit Bull                                    3
Great Pyrenees/Pit Bull                                   3
Shih Tzu/Pit Bull                                         3
American Pit Bull Terrier/Labrador Retriever              3
American Staffordshire Terrier/Pit Bull                   3
Labrador Retriever/American Pit Bull Terrier              3
Pit Bull/Rat Terrier                                      3
Dalmatian/Pit Bull                                        3
Rottweiler/Pit Bull                                       3
American Pit Bull Terrier/Pit Bull                        2
Australian Kelpie/American Pit Bull Terrier               2
Rhod Ridgeback/Pit Bull                                   2
Pit Bull/Bull Terrier                                     2
Bulldog/Pit Bull                                          2
Anatol Shepherd/Pit Bull                                  2
Boston Terrier/Pit Bull                                   2
American Pit Bull Terrier/Catahoula                       2
Pit Bull/Carolina Dog                                     2
Bull Terrier/Pit Bull                                     2
Pit Bull/Pit Bull                                         2
Akita/Pit Bull                                            2
American Pit Bull Terrier/American Pit Bull Terrier       2
Pit Bull/Beagle                                           2
Siberian Husky/American Pit Bull Terrier                  2
Australian Shepherd/Pit Bull                              2
Pit Bull/Flat Coat Retriever                              2
Pit Bull/English Bulldog                                  2
Beagle/Pit Bull                                           2
Catahoula/American Pit Bull Terrier                       2
Pit Bull/Pug                                              2
Pit Bull/French Bulldog                                   2
American Pit Bull Terrier/Boxer                           1
Pit Bull/Jindo                                            1
Canaan Dog/Pit Bull                                       1
American Pit Bull Terrier/Chinese Sharpei                 1
American Pit Bull Terrier/Pointer                         1
Australian Cattle Dog/American Pit Bull Terrier           1
English Bulldog/Pit Bull                                  1
Pit Bull/American Bulldog                                 1
Harrier/Pit Bull                                          1
American Pit Bull Terrier/American Bulldog                1
Cardigan Welsh Corgi/Pit Bull                             1
Golden Retriever/Pit Bull                                 1
Pit Bull/Dogue De Bordeaux                                1
Pit Bull/Pharaoh Hound                                    1
Rat Terrier/American Pit Bull Terrier                     1
Mastiff/American Pit Bull Terrier                         1
Pit Bull/Cardigan Welsh Corgi                             1
Pit Bull/Anatol Shepherd                                  1
Pit Bull/Siberian Husky                                   1
Rat Terrier/Pit Bull                                      1
Pit Bull/Jack Russell Terrier                             1
Pit Bull/Queensland Heeler                                1
Pit Bull/Belgian Malinois                                 1
Ibizan Hound/Pit Bull                                     1
Pit Bull/St. Bernard Smooth Coat                          1
Pit Bull/Doberman Pinsch                                  1
Dogo Argentino/Pit Bull                                   1
Boxer/American Pit Bull Terrier                           1
Pembroke Welsh Corgi/Pit Bull                             1
Swiss Hound/Pit Bull                                      1
Neapolitan Mastiff/Pit Bull                               1
Pit Bull/Border Collie                                    1
Pug/Pit Bull                                              1
Pit Bull/American Foxhound                                1
Irish Wolfhound/American Pit Bull Terrier                 1
Name: count, dtype: int64

#### Verify that "Pit Bull" is not written as "Pitbull" anywhere in the dataset:

In [315]:
intakes[intakes["breed"].str.contains("pitbull", case=False, na=False)]["breed"].value_counts()

Series([], Name: count, dtype: int64)

### Labrador Retriever Breed Variations

In [316]:
intakes[intakes["breed"].str.contains("labrador", case=False, na=False)]["breed"].value_counts()

breed
Labrador Retriever Mix                               4841
Labrador Retriever                                    241
Labrador Retriever/Pit Bull                           218
German Shepherd/Labrador Retriever                    160
Labrador Retriever/German Shepherd                    140
Pit Bull/Labrador Retriever                           107
Labrador Retriever/Border Collie                       80
Labrador Retriever/Australian Cattle Dog               74
Border Collie/Labrador Retriever                       71
Australian Cattle Dog/Labrador Retriever               62
Labrador Retriever/Boxer                               52
Labrador Retriever/Great Pyrenees                      51
Labrador Retriever/Beagle                              45
Labrador Retriever/Pointer                             43
Labrador Retriever/Chow Chow                           39
Boxer/Labrador Retriever                               38
Pointer/Labrador Retriever                             37
Labrador Retriever/Australian Shepherd                 32
Labrador Retriever/Plott Hound                         31
Labrador Retriever/Rottweiler                          30
Great Pyrenees/Labrador Retriever                      30
Catahoula/Labrador Retriever                           27
Labrador Retriever/Catahoula                           26
Australian Shepherd/Labrador Retriever                 24
Golden Retriever/Labrador Retriever                    23
Labrador Retriever/Golden Retriever                    23
Plott Hound/Labrador Retriever                         23
Anatol Shepherd/Labrador Retriever                     22
Beagle/Labrador Retriever                              22
Labrador Retriever/Chinese Sharpei                     21
Rottweiler/Labrador Retriever                          21
Labrador Retriever/Anatol Shepherd                     21
Labrador Retriever/Siberian Husky                      20
Chinese Sharpei/Labrador Retriever                     19
Labrador Retriever/Doberman Pinsch                     17
Labrador Retriever/Basset Hound                        16
Rhod Ridgeback/Labrador Retriever                      15
Basset Hound/Labrador Retriever                        15
Labrador Retriever/Blue Lacy                           15
Dachshund/Labrador Retriever                           15
Siberian Husky/Labrador Retriever                      15
Labrador Retriever/Dachshund                           15
Chow Chow/Labrador Retriever                           14
Great Dane/Labrador Retriever                          14
Labrador Retriever/Australian Kelpie                   14
Labrador Retriever/Whippet                             13
Labrador Retriever/Greyhound                           12
Labrador Retriever/Jack Russell Terrier                11
Cocker Spaniel/Labrador Retriever                      11
Standard Poodle/Labrador Retriever                     10
Collie Smooth/Labrador Retriever                       10
Labrador Retriever/Queensland Heeler                   10
Labrador Retriever/Great Dane                          10
Labrador Retriever/Standard Poodle                     10
Labrador Retriever/Rhod Ridgeback                       8
Labrador Retriever/Mastiff                              8
Weimaraner/Labrador Retriever                           7
Labrador Retriever/Collie Smooth                        7
Dalmatian/Labrador Retriever                            7
American Staffordshire Terrier/Labrador Retriever       7
Labrador Retriever/Flat Coat Retriever                  7
Labrador Retriever/Weimaraner                           7
Pug/Labrador Retriever                                  6
Labrador Retriever/Miniature Poodle                     6
Labrador Retriever/Dalmatian                            6
Labrador Retriever/American Bulldog                     6
Labrador Retriever/Black/Tan Hound                      6
Labrador Retriever/Labrador Retriever                   6
Labrador Retriever/Vizsla                               6
Labrador Retriever/Alaskan Husky                        6
Jack Russell Terrier/Labrador Retriever                 5
Staffordshire/Labrador Retriever                        5
Labrador Retriever/German Shorthair Pointer             5
Rat Terrier/Labrador Retriever                          5
Labrador Retriever/Staffordshire                        5
Vizsla/Labrador Retriever                               5
Whippet/Labrador Retriever                              5
American Bulldog/Labrador Retriever                     5
Doberman Pinsch/Labrador Retriever                      5
Labrador Retriever/Black Mouth Cur                      5
Australian Kelpie/Labrador Retriever                    5
Redbone Hound/Labrador Retriever                        5
Black Mouth Cur/Labrador Retriever                      5
Labrador Retriever/Chesa Bay Retr                       4
Labrador Retriever/Standard Schnauzer                   4
Newfoundland/Labrador Retriever                         3
Flat Coat Retriever/Labrador Retriever                  3
Dutch Shepherd/Labrador Retriever                       3
Brittany/Labrador Retriever                             3
Labrador Retriever/Redbone Hound                        3
American Pit Bull Terrier/Labrador Retriever            3
Greyhound/Labrador Retriever                            3
Miniature Poodle/Labrador Retriever                     3
Labrador Retriever/American Pit Bull Terrier            3
Chesa Bay Retr/Labrador Retriever                       3
Black/Tan Hound/Labrador Retriever                      3
Labrador Retriever/Shiba Inu                            3
Cardigan Welsh Corgi/Labrador Retriever                 3
Labrador Retriever/Cocker Spaniel                       2
Labrador Retriever/English Springer Spaniel             2
Harrier/Labrador Retriever                              2
Labrador Retriever/Pembroke Welsh Corgi                 2
Labrador Retriever/Smooth Fox Terrier                   2
Alaskan Malamute/Labrador Retriever                     2
Treeing Walker Coonhound/Labrador Retriever             2
Labrador Retriever/Collie Rough                         2
Soft Coated Wheaten Terrier/Labrador Retriever          2
Collie Rough/Labrador Retriever                         2
Carolina Dog/Labrador Retriever                         2
Labrador Retriever/Border Terrier                       2
Labrador Retriever/Newfoundland                         2
Labrador Retriever/English Pointer                      2
Airedale Terrier/Labrador Retriever                     2
Irish Terrier/Labrador Retriever                        2
German Wirehaired Pointer/Labrador Retriever            2
Manchester Terrier/Labrador Retriever                   2
Mastiff/Labrador Retriever                              2
Alaskan Husky/Labrador Retriever                        2
Labrador Retriever/Boston Terrier                       2
Dogo Argentino/Labrador Retriever                       2
Blue Lacy/Labrador Retriever                            2
Labrador Retriever/Bloodhound                           2
Labrador Retriever/Akita                                1
Labrador Retriever/Cardigan Welsh Corgi                 1
American Foxhound/Labrador Retriever                    1
Labrador Retriever/Rat Terrier                          1
Bloodhound/Labrador Retriever                           1
Queensland Heeler/Labrador Retriever                    1
Labrador Retriever/Treeing Walker Coonhound             1
Labrador Retriever/Chihuahua Shorthair                  1
Labrador Retriever/Saluki                               1
Bulldog/Labrador Retriever                              1
Kuvasz/Labrador Retriever                               1
Pembroke Welsh Corgi/Labrador Retriever                 1
Chihuahua Shorthair/Labrador Retriever                  1
English Pointer/Labrador Retriever                      1
Labrador Retriever/American Foxhound                    1
Labrador Retriever/Finnish Spitz                        1
Labrador Retriever/St. Bernard Smooth Coat              1
Labrador Retriever/St. Bernard Rough Coat               1
Labrador Retriever/Pug                                  1
Labrador Retriever/Patterdale Terr                      1
Labrador Retriever/Bullmastiff                          1
St. Bernard Rough Coat/Labrador Retriever               1
Welsh Springer Spaniel/Labrador Retriever               1
Afghan Hound/Labrador Retriever                         1
Schnauzer Giant/Labrador Retriever                      1
Labrador Retriever/Irish Setter                         1
Labrador Retriever/Brittany                             1
Labrador Retriever/American Staffordshire Terrier       1
Labrador Retriever/Beauceron                            1
Smooth Fox Terrier/Labrador Retriever                   1
Miniature Schnauzer/Labrador Retriever                  1
English Foxhound/Labrador Retriever                     1
Basenji/Labrador Retriever                              1
Labrador Retriever/Spanish Water Dog                    1
Saluki/Labrador Retriever                               1
Labrador Retriever/Harrier                              1
Labrador Retriever/Pharaoh Hound                        1
Border Terrier/Labrador Retriever                       1
English Springer Spaniel/Labrador Retriever             1
Labrador Retriever/Alaskan Malamute                     1
Boston Terrier/Labrador Retriever                       1
Jindo/Labrador Retriever                                1
Akita/Labrador Retriever                                1
Standard Schnauzer/Labrador Retriever                   1
Name: count, dtype: int64

#### Verify that "Labrador Retriever" is not abbreviated as "Lab" anywhere in the dataset:

In [317]:
intakes[intakes["breed"].str.contains("^lab ", case=False, na=False)]["breed"].value_counts()

Series([], Name: count, dtype: int64)

### Chihuahua Breed Variations

In [318]:
intakes[intakes["breed"].str.contains("chihuahua", case=False, na=False)]["breed"].value_counts()

breed
Chihuahua Shorthair Mix                            4860
Chihuahua Longhair Mix                              371
Chihuahua Shorthair/Dachshund                       252
Chihuahua Shorthair                                 204
Dachshund/Chihuahua Shorthair                       179
Chihuahua Shorthair/Rat Terrier                      61
Chihuahua Shorthair/Jack Russell Terrier             59
Chihuahua Shorthair/Pug                              51
Rat Terrier/Chihuahua Shorthair                      49
Jack Russell Terrier/Chihuahua Shorthair             41
Pug/Chihuahua Shorthair                              37
Chihuahua Shorthair/Cardigan Welsh Corgi             30
Miniature Pinscher/Chihuahua Shorthair               25
Cairn Terrier/Chihuahua Shorthair                    23
Beagle/Chihuahua Shorthair                           23
Yorkshire Terrier/Chihuahua Shorthair                23
Chihuahua Shorthair/Beagle                           21
Chihuahua Shorthair/Yorkshire Terrier                21
Chihuahua Shorthair/Miniature Pinscher               19
Cardigan Welsh Corgi/Chihuahua Shorthair             19
Chihuahua Shorthair/Boston Terrier                   17
Chihuahua Shorthair/Cairn Terrier                    17
Chihuahua Longhair                                   16
Boston Terrier/Chihuahua Shorthair                   14
Dachshund Wirehair/Chihuahua Shorthair               13
Pit Bull/Chihuahua Shorthair                         12
Chihuahua Shorthair/Italian Greyhound                12
Border Terrier/Chihuahua Shorthair                   11
Manchester Terrier/Chihuahua Shorthair               11
Chihuahua Shorthair/Pomeranian                       11
Chihuahua Longhair/Pomeranian                        10
Pomeranian/Chihuahua Longhair                        10
Yorkshire Terrier/Chihuahua Longhair                  9
Chihuahua Shorthair/Dachshund Wirehair                8
Chihuahua Shorthair/Manchester Terrier                8
Chihuahua Shorthair/Border Terrier                    7
Chihuahua Shorthair/Pit Bull                          7
Chihuahua Shorthair/Whippet                           6
Chihuahua Shorthair/Swedish Vallhund                  6
Chihuahua Longhair/Dachshund                          6
Chihuahua Shorthair/Pembroke Welsh Corgi              6
Chihuahua Shorthair/Miniature Schnauzer               6
Chihuahua Longhair/Cairn Terrier                      6
Dachshund Longhair/Chihuahua Shorthair                6
Chihuahua Shorthair/Miniature Poodle                  6
Pembroke Welsh Corgi/Chihuahua Shorthair              6
Miniature Schnauzer/Chihuahua Shorthair               5
Basenji/Chihuahua Shorthair                           5
Chihuahua Longhair/Maltese                            5
Pomeranian/Chihuahua Shorthair                        5
Carolina Dog/Chihuahua Shorthair                      5
Wire Hair Fox Terrier/Chihuahua Shorthair             5
Australian Shepherd/Chihuahua Shorthair               5
Chihuahua Shorthair/Australian Cattle Dog             4
Miniature Poodle/Chihuahua Shorthair                  4
Chihuahua Shorthair/Wire Hair Fox Terrier             4
Chihuahua Longhair/Cardigan Welsh Corgi               4
Cairn Terrier/Chihuahua Longhair                      4
Norfolk Terrier/Chihuahua Shorthair                   4
Parson Russell Terrier/Chihuahua Shorthair            4
Shih Tzu/Chihuahua Shorthair                          3
Chihuahua Shorthair/Smooth Fox Terrier                3
Cocker Spaniel/Chihuahua Shorthair                    3
Chihuahua Shorthair/Basset Hound                      3
Chihuahua Longhair/Pekingese                          3
Chihuahua Shorthair/German Shepherd                   3
Queensland Heeler/Chihuahua Shorthair                 3
Chihuahua Shorthair/Shih Tzu                          3
Dachshund/Chihuahua Longhair                          3
Chihuahua Shorthair/Basenji                           3
Schipperke/Chihuahua Shorthair                        3
Chihuahua Longhair/Yorkshire Terrier                  3
Chihuahua Shorthair/Schipperke                        3
Bruss Griffon/Chihuahua Shorthair                     3
Chihuahua Longhair/Jack Russell Terrier               3
Chihuahua Shorthair/Mexican Hairless                  3
French Bulldog/Chihuahua Shorthair                    3
Chihuahua Longhair/Dachshund Wirehair                 2
Chihuahua Shorthair/French Bulldog                    2
Chihuahua Shorthair/Norfolk Terrier                   2
Dachshund Wirehair/Chihuahua Longhair                 2
Chihuahua Longhair/Papillon                           2
Chihuahua Shorthair/Chinese Sharpei                   2
Whippet/Chihuahua Shorthair                           2
Chihuahua Shorthair/Pekingese                         2
Chihuahua Longhair/West Highland                      2
Chihuahua Shorthair/Cocker Spaniel                    2
Italian Greyhound/Chihuahua Shorthair                 2
Chihuahua Longhair/Dachshund Longhair                 2
Basenji/Chihuahua Longhair                            2
Chihuahua Longhair/Rat Terrier                        2
Chihuahua Shorthair/Welsh Terrier                     2
Pug/Chihuahua Longhair                                2
Miniature Schnauzer/Chihuahua Longhair                2
Dachshund Longhair/Chihuahua Longhair                 2
Cavalier Span/Chihuahua Shorthair                     2
Papillon/Chihuahua Shorthair                          2
Chihuahua Shorthair/Finnish Spitz                     2
Chihuahua Shorthair/Toy Fox Terrier                   2
Pekingese/Chihuahua Shorthair                         2
Chihuahua Shorthair/Catahoula                         2
Tibetan Spaniel/Chihuahua Longhair                    1
Chihuahua Shorthair/Parson Russell Terrier            1
Chihuahua Longhair/Silky Terrier                      1
Chihuahua Shorthair/Bichon Frise                      1
Labrador Retriever/Chihuahua Shorthair                1
Brittany/Chihuahua Shorthair                          1
Rat Terrier/Chihuahua Longhair                        1
Chihuahua Shorthair/Labrador Retriever                1
Cardigan Welsh Corgi/Chihuahua Longhair               1
Chinese Crested/Chihuahua Longhair                    1
Chihuahua Longhair/Italian Greyhound                  1
Chihuahua Longhair/Cavalier Span                      1
Miniature Poodle/Chihuahua Longhair                   1
Beagle/Chihuahua Longhair                             1
Maltese/Chihuahua Shorthair                           1
Chihuahua Shorthair/Rhod Ridgeback                    1
Chihuahua Longhair/Miniature Poodle                   1
Chihuahua Longhair/Queensland Heeler                  1
Bruss Griffon/Chihuahua Longhair                      1
Manchester Terrier/Chihuahua Longhair                 1
Chihuahua Shorthair/Cirneco                           1
Chihuahua Longhair/Border Terrier                     1
Cocker Spaniel/Chihuahua Longhair                     1
Chihuahua Shorthair/Border Collie                     1
Cavalier Span/Chihuahua Longhair                      1
Smooth Fox Terrier/Chihuahua Shorthair                1
Chihuahua Shorthair/Shetland Sheepdog                 1
Australian Cattle Dog/Chihuahua Shorthair             1
Pembroke Welsh Corgi/Chihuahua Longhair               1
Australian Kelpie/Chihuahua Shorthair                 1
Chihuahua Longhair/Norfolk Terrier                    1
Chihuahua Shorthair/Shiba Inu                         1
Toy Poodle/Chihuahua Shorthair                        1
Chihuahua Longhair/Chihuahua Shorthair                1
Soft Coated Wheaten Terrier/Chihuahua Shorthair       1
Chihuahua Longhair/Cocker Spaniel                     1
Feist/Chihuahua Shorthair                             1
Border Terrier/Chihuahua Longhair                     1
West Highland/Chihuahua Shorthair                     1
Chihuahua Shorthair/Lhasa Apso                        1
Chihuahua Longhair/Pug                                1
Chihuahua Shorthair/Queensland Heeler                 1
Patterdale Terr/Chihuahua Shorthair                   1
Chihuahua Shorthair/Australian Terrier                1
Chihuahua Shorthair/Cavalier Span                     1
Jack Russell Terrier/Chihuahua Longhair               1
Chihuahua Shorthair/Papillon                          1
Shih Tzu/Chihuahua Longhair                           1
Chihuahua Shorthair/Boxer                             1
Chihuahua Shorthair/Rottweiler                        1
Chihuahua Shorthair/Affenpinscher                     1
Shetland Sheepdog/Chihuahua Longhair                  1
Name: count, dtype: int64

### Dachshund Breed Variations

In [319]:
intakes[intakes["breed"].str.contains("dachshund", case=False, na=False)]["breed"].value_counts()

breed
Dachshund Mix                               813
Chihuahua Shorthair/Dachshund               252
Dachshund/Chihuahua Shorthair               179
Dachshund                                   102
Dachshund Longhair Mix                       95
Dachshund Wirehair Mix                       87
Dachshund/Beagle                             24
Beagle/Dachshund                             18
Dachshund Longhair                           17
Dachshund/Rat Terrier                        15
Dachshund/Labrador Retriever                 15
Labrador Retriever/Dachshund                 15
Dachshund Wirehair/Chihuahua Shorthair       13
Jack Russell Terrier/Dachshund               12
Dachshund Wirehair/Miniature Poodle          11
Dachshund/Manchester Terrier                 10
Dachshund Wirehair/Border Terrier             8
Chihuahua Shorthair/Dachshund Wirehair        8
Miniature Poodle/Dachshund                    8
Dachshund/Pit Bull                            8
Manchester Terrier/Dachshund                  7
Pit Bull/Dachshund                            6
Chihuahua Longhair/Dachshund                  6
Dachshund Longhair/Chihuahua Shorthair        6
Dachshund Wirehair                            5
Rat Terrier/Dachshund                         5
Dachshund/Jack Russell Terrier                5
Dachshund/Australian Cattle Dog               5
Dachshund/Cardigan Welsh Corgi                4
Shih Tzu/Dachshund                            4
Dachshund/Pug                                 4
Dachshund/Whippet                             4
Cairn Terrier/Dachshund                       4
Dachshund/Shih Tzu                            4
Border Collie/Dachshund                       4
Dachshund Wirehair/Toy Poodle                 4
Dachshund/Bloodhound                          3
Dachshund Longhair/Cardigan Welsh Corgi       3
Dachshund/Catahoula                           3
Dachshund/Miniature Poodle                    3
Border Terrier/Dachshund                      3
Dachshund/Chihuahua Longhair                  3
Australian Cattle Dog/Dachshund               3
Cocker Spaniel/Dachshund                      3
Whippet/Dachshund                             3
Boston Terrier/Dachshund                      3
Wire Hair Fox Terrier/Dachshund               3
Miniature Pinscher/Dachshund                  3
Miniature Schnauzer/Dachshund Wirehair        3
Dachshund/Miniature Pinscher                  3
Dachshund Wirehair/Miniature Schnauzer        3
Chihuahua Longhair/Dachshund Wirehair         2
Queensland Heeler/Dachshund                   2
Dachshund Wirehair/Norfolk Terrier            2
Black Mouth Cur/Dachshund                     2
Golden Retriever/Dachshund                    2
Dachshund/Parson Russell Terrier              2
Dachshund/Harrier                             2
Dachshund Wirehair/Chihuahua Longhair         2
Jack Russell Terrier/Dachshund Wirehair       2
Bruss Griffon/Dachshund                       2
Australian Kelpie/Dachshund                   2
Cairn Terrier/Dachshund Wirehair              2
Dachshund Longhair/Cocker Spaniel             2
Redbone Hound/Dachshund                       2
Dachshund Longhair/Miniature Schnauzer        2
Chihuahua Longhair/Dachshund Longhair         2
Dachshund/Basset Hound                        2
Basset Hound/Dachshund                        2
Dachshund Wirehair/Rat Terrier                2
Dachshund/Greyhound                           2
Dachshund/Bull Terrier                        2
Dachshund/Yorkshire Terrier                   2
Dachshund Longhair/Chihuahua Longhair         2
Dachshund/English Foxhound                    2
Cardigan Welsh Corgi/Dachshund                2
Vizsla/Dachshund                              2
Dachshund/Belgian Malinois                    2
Dachshund Longhair/Maltese                    2
Dachshund Wirehair/Cairn Terrier              2
Dachshund/Dachshund                           1
Dachshund Longhair/Tibetan Spaniel            1
Norfolk Terrier/Dachshund Wirehair            1
Dachshund/Chinese Sharpei                     1
Dachshund/Australian Kelpie                   1
Dachshund Longhair/Golden Retriever           1
Lhasa Apso/Dachshund                          1
Dachshund Wirehair/Yorkshire Terrier          1
Shetland Sheepdog/Dachshund Longhair          1
Dachshund/Wire Hair Fox Terrier               1
Dachshund/Swedish Vallhund                    1
Toy Fox Terrier/Dachshund                     1
Boykin Span/Dachshund                         1
Shiba Inu/Dachshund                           1
Dachshund/Border Collie                       1
Dachshund Longhair/Australian Shepherd        1
Treeing Walker Coonhound/Dachshund            1
Dachshund Longhair/Cairn Terrier              1
Australian Shepherd/Dachshund                 1
Dachshund/Pomeranian                          1
Dachshund/Cavalier Span                       1
Dachshund Wirehair/West Highland              1
Border Terrier/Dachshund Wirehair             1
Dachshund Longhair/Pomeranian                 1
Dachshund Longhair/Miniature Poodle           1
Dachshund Longhair/Pembroke Welsh Corgi       1
Dachshund/Pembroke Welsh Corgi                1
Norfolk Terrier/Dachshund                     1
Toy Poodle/Dachshund                          1
Dachshund/English Bulldog                     1
Dachshund Stan Mix                            1
Dachshund/Norfolk Terrier                     1
English Bulldog/Dachshund                     1
Dachshund/German Pinscher                     1
Dachshund/German Shepherd                     1
French Bulldog/Dachshund                      1
Maltese/Dachshund                             1
Dachshund Wirehair/Standard Poodle            1
Dachshund/American Staffordshire Terrier      1
Dachshund Wirehair/Pbgv                       1
Dachshund/Boxer                               1
Pembroke Welsh Corgi/Dachshund                1
Dachshund Longhair/Toy Poodle                 1
Plott Hound/Dachshund                         1
Dachshund/Havanese                            1
Dachshund/Shetland Sheepdog                   1
Miniature Schnauzer/Dachshund                 1
Cocker Spaniel/Dachshund Longhair             1
Miniature Schnauzer/Dachshund Longhair        1
Dachshund Wirehair/Shih Tzu                   1
Finnish Spitz/Dachshund                       1
Yorkshire Terrier/Dachshund Wirehair          1
Dachshund/Blue Lacy                           1
Yorkshire Terrier/Dachshund                   1
Name: count, dtype: int64

### German Shepherd Breed Variations

In [320]:
intakes[intakes["breed"].str.contains("german shepherd", case=False, na=False)]["breed"].value_counts()

breed
German Shepherd Mix                                   1963
German Shepherd                                        236
German Shepherd/Labrador Retriever                     160
Labrador Retriever/German Shepherd                     140
Siberian Husky/German Shepherd                          33
German Shepherd/Chow Chow                               28
Border Collie/German Shepherd                           28
Australian Cattle Dog/German Shepherd                   23
German Shepherd/Siberian Husky                          22
German Shepherd/Rottweiler                              21
German Shepherd/Australian Cattle Dog                   20
Beagle/German Shepherd                                  19
German Shepherd/Pit Bull                                16
German Shepherd/Boxer                                   15
Chow Chow/German Shepherd                               15
Rottweiler/German Shepherd                              14
Pit Bull/German Shepherd                                11
German Shepherd/Border Collie                           11
German Shepherd/Black Mouth Cur                         10
German Shepherd/Alaskan Husky                           10
German Shepherd/Mastiff                                  9
German Shepherd/Australian Shepherd                      9
German Shepherd/Doberman Pinsch                          7
German Shepherd/Black/Tan Hound                          7
German Shepherd/Golden Retriever                         6
German Shepherd/Catahoula                                6
German Shepherd/Alaskan Malamute                         6
Great Pyrenees/German Shepherd                           6
German Shepherd/Collie Rough                             6
Catahoula/German Shepherd                                6
Black Mouth Cur/German Shepherd                          6
German Shepherd/Cardigan Welsh Corgi                     6
German Shepherd/Pembroke Welsh Corgi                     5
German Shepherd/Chinese Sharpei                          5
Collie Rough/German Shepherd                             5
German Shepherd/Great Pyrenees                           4
Doberman Pinsch/German Shepherd                          4
Alaskan Husky/German Shepherd                            4
German Shepherd/Australian Kelpie                        4
Cardigan Welsh Corgi/German Shepherd                     4
German Shepherd/Anatol Shepherd                          4
Anatol Shepherd/German Shepherd                          4
German Shepherd/Nova Scotia Duck Tolling Retriever       4
Treeing Walker Coonhound/German Shepherd                 3
Chihuahua Shorthair/German Shepherd                      3
Collie Smooth/German Shepherd                            3
German Shepherd/Redbone Hound                            3
Rhod Ridgeback/German Shepherd                           3
German Shepherd/Plott Hound                              3
Golden Retriever/German Shepherd                         3
German Shepherd/Collie Smooth                            3
Flat Coat Retriever/German Shepherd                      3
Standard Schnauzer/German Shepherd                       3
German Shepherd/Bull Terrier                             2
Australian Kelpie/German Shepherd                        2
Australian Shepherd/German Shepherd                      2
Belgian Tervuren/German Shepherd                         2
Shiba Inu/German Shepherd                                2
Alaskan Malamute/German Shepherd                         2
German Shepherd/Akita                                    2
Pembroke Welsh Corgi/German Shepherd                     2
German Shepherd/Great Dane                               2
Boxer/German Shepherd                                    2
Akita/German Shepherd                                    2
German Shepherd/Weimaraner                               1
Black/Tan Hound/German Shepherd                          1
German Shepherd/Pointer                                  1
Belgian Malinois/German Shepherd                         1
German Shepherd/Whippet                                  1
Whippet/German Shepherd                                  1
Queensland Heeler/German Shepherd                        1
German Shepherd/Swedish Vallhund                         1
German Shepherd/Vizsla                                   1
Harrier/German Shepherd                                  1
German Shepherd/English Coonhound                        1
Great Dane/German Shepherd                               1
Wire Hair Fox Terrier/German Shepherd                    1
Dachshund/German Shepherd                                1
St. Bernard Rough Coat/German Shepherd                   1
Mastiff/German Shepherd                                  1
German Shepherd/Ibizan Hound                             1
English Coonhound/German Shepherd                        1
Plott Hound/German Shepherd                              1
German Shepherd/Bloodhound                               1
German Shepherd/Smooth Fox Terrier                       1
German Shepherd/Beagle                                   1
German Shepherd/German Shepherd                          1
Leonberger/German Shepherd                               1
German Shepherd/Greyhound                                1
German Shepherd/Basenji                                  1
Vizsla/German Shepherd                                   1
Name: count, dtype: int64

### Husky Breed Variations

In [321]:
intakes[intakes["breed"].str.contains("husky", case=False, na=False)]["breed"].value_counts()

breed
Siberian Husky Mix                          442
Siberian Husky                              115
Alaskan Husky Mix                            57
Siberian Husky/German Shepherd               33
German Shepherd/Siberian Husky               22
Labrador Retriever/Siberian Husky            20
Siberian Husky/Labrador Retriever            15
Siberian Husky/Australian Cattle Dog         13
German Shepherd/Alaskan Husky                10
Alaskan Husky                                 9
Siberian Husky/Border Collie                  6
Labrador Retriever/Alaskan Husky              6
Siberian Husky/Pit Bull                       4
Alaskan Husky/German Shepherd                 4
Rottweiler/Siberian Husky                     4
Pit Bull/Alaskan Husky                        4
Akita/Siberian Husky                          4
Alaskan Husky/Australian Shepherd             3
Siberian Husky/Alaskan Malamute               3
Chow Chow/Siberian Husky                      2
Australian Cattle Dog/Siberian Husky          2
Border Collie/Alaskan Husky                   2
Siberian Husky/American Pit Bull Terrier      2
Siberian Husky/Chinese Sharpei                2
Catahoula/Alaskan Husky                       2
Alaskan Husky/Labrador Retriever              2
Great Pyrenees/Siberian Husky                 1
Great Pyrenees/Alaskan Husky                  1
Australian Cattle Dog/Alaskan Husky           1
Siberian Husky/Beagle                         1
Alaskan Malamute/Alaskan Husky                1
Anatol Shepherd/Siberian Husky                1
Siberian Husky/Rottweiler                     1
Siberian Husky/Great Pyrenees                 1
Pit Bull/Siberian Husky                       1
Siberian Husky/Catahoula                      1
Siberian Husky/Australian Shepherd            1
Border Collie/Siberian Husky                  1
Australian Kelpie/Alaskan Husky               1
Siberian Husky/Anatol Shepherd                1
American Eskimo/Alaskan Husky                 1
Siberian Husky/Cardigan Welsh Corgi           1
Black/Tan Hound/Siberian Husky                1
Black Mouth Cur/Siberian Husky                1
Shiba Inu/Siberian Husky                      1
Alaskan Husky/Border Collie                   1
Australian Shepherd/Siberian Husky            1
Collie Smooth/Siberian Husky                  1
Catahoula/Siberian Husky                      1
Name: count, dtype: int64

### Australian Cattle Dog Breed Variations

In [322]:
intakes[intakes["breed"].str.contains("australian cattle", case=False, na=False)]["breed"].value_counts()

breed
Australian Cattle Dog Mix                               1105
Australian Cattle Dog                                     87
Labrador Retriever/Australian Cattle Dog                  74
Australian Cattle Dog/Labrador Retriever                  62
Pit Bull/Australian Cattle Dog                            29
Australian Cattle Dog/German Shepherd                     23
German Shepherd/Australian Cattle Dog                     20
Australian Cattle Dog/Pit Bull                            18
Australian Cattle Dog/Border Collie                       17
Border Collie/Australian Cattle Dog                       15
Australian Cattle Dog/Boxer                               13
Siberian Husky/Australian Cattle Dog                      13
Jack Russell Terrier/Australian Cattle Dog                13
Australian Cattle Dog/Beagle                              11
Australian Cattle Dog/Pointer                             10
Cardigan Welsh Corgi/Australian Cattle Dog                 9
Catahoula/Australian Cattle Dog                            9
Australian Cattle Dog/Akita                                8
Beagle/Australian Cattle Dog                               8
Chow Chow/Australian Cattle Dog                            8
Australian Cattle Dog/Australian Shepherd                  8
Boxer/Australian Cattle Dog                                7
Australian Cattle Dog/Staffordshire                        7
Pointer/Australian Cattle Dog                              7
Basset Hound/Australian Cattle Dog                         6
Australian Cattle Dog/Jack Russell Terrier                 6
Australian Shepherd/Australian Cattle Dog                  6
Australian Cattle Dog/Chow Chow                            5
Great Pyrenees/Australian Cattle Dog                       5
Australian Cattle Dog/Catahoula                            5
Dachshund/Australian Cattle Dog                            5
Basenji/Australian Cattle Dog                              4
Chihuahua Shorthair/Australian Cattle Dog                  4
Australian Cattle Dog/Pembroke Welsh Corgi                 4
Australian Cattle Dog/Cardigan Welsh Corgi                 4
Rottweiler/Australian Cattle Dog                           4
Australian Cattle Dog/Plott Hound                          4
Australian Cattle Dog/Chinese Sharpei                      3
Australian Cattle Dog/Great Pyrenees                       3
Australian Cattle Dog/Bull Terrier                         3
Australian Cattle Dog/Dachshund                            3
Australian Cattle Dog/German Shorthair Pointer             3
Miniature Poodle/Australian Cattle Dog                     3
Australian Cattle Dog/Basenji                              3
Akita/Australian Cattle Dog                                3
Carolina Dog/Australian Cattle Dog                         3
Doberman Pinsch/Australian Cattle Dog                      2
Australian Cattle Dog/Rhod Ridgeback                       2
Plott Hound/Australian Cattle Dog                          2
Anatol Shepherd/Australian Cattle Dog                      2
Australian Cattle Dog/Cairn Terrier                        2
Australian Cattle Dog/Queensland Heeler                    2
Australian Cattle Dog/Bloodhound                           2
Rat Terrier/Australian Cattle Dog                          2
Australian Cattle Dog/Boston Terrier                       2
Australian Cattle Dog/Parson Russell Terrier               2
Golden Retriever/Australian Cattle Dog                     2
Australian Cattle Dog/Collie Smooth                        2
Australian Cattle Dog/Anatol Shepherd                      2
Australian Cattle Dog/Siberian Husky                       2
Staffordshire/Australian Cattle Dog                        2
Australian Cattle Dog/Dalmatian                            2
Australian Cattle Dog/Whippet                              2
Queensland Heeler/Australian Cattle Dog                    2
Dalmatian/Australian Cattle Dog                            2
Black Mouth Cur/Australian Cattle Dog                      2
Newfoundland/Australian Cattle Dog                         1
Whippet/Australian Cattle Dog                              1
Australian Cattle Dog/Belgian Malinois                     1
Miniature Schnauzer/Australian Cattle Dog                  1
German Shorthair Pointer/Australian Cattle Dog             1
Australian Cattle Dog/Golden Retriever                     1
Australian Cattle Dog/Treeing Walker Coonhound             1
Australian Cattle Dog/Black Mouth Cur                      1
Australian Cattle Dog/Alaskan Husky                        1
Australian Cattle Dog/English Coonhound                    1
Redbone Hound/Australian Cattle Dog                        1
Australian Cattle Dog/American Pit Bull Terrier            1
Bluetick Hound/Australian Cattle Dog                       1
Australian Kelpie/Australian Cattle Dog                    1
Great Dane/Australian Cattle Dog                           1
Treeing Walker Coonhound/Australian Cattle Dog             1
Miniature Pinscher/Australian Cattle Dog                   1
Australian Cattle Dog/American Staffordshire Terrier       1
Rhod Ridgeback/Australian Cattle Dog                       1
Australian Cattle Dog/Chihuahua Shorthair                  1
Australian Cattle Dog/Rat Terrier                          1
Australian Cattle Dog/Vizsla                               1
Australian Cattle Dog/Pug                                  1
Australian Cattle Dog/Chinese Crested                      1
Chinese Sharpei/Australian Cattle Dog                      1
Pharaoh Hound/Australian Cattle Dog                        1
English Coonhound/Australian Cattle Dog                    1
Blue Lacy/Australian Cattle Dog                            1
Bulldog/Australian Cattle Dog                              1
Pembroke Welsh Corgi/Australian Cattle Dog                 1
Collie Rough/Australian Cattle Dog                         1
Australian Cattle Dog/Australian Kelpie                    1
Flat Coat Retriever/Australian Cattle Dog                  1
Australian Cattle Dog/Collie Rough                         1
Australian Cattle Dog/American Foxhound                    1
American Staffordshire Terrier/Australian Cattle Dog       1
Papillon/Australian Cattle Dog                             1
English Bulldog/Australian Cattle Dog                      1
Name: count, dtype: int64

### Staffordshire Breed Variations

In [323]:
intakes[intakes["breed"].str.contains("staffordshire", case=False, na=False)]["breed"].value_counts()

breed
Staffordshire Mix                                       385
American Staffordshire Terrier Mix                      219
American Staffordshire Terrier                           26
Staffordshire                                            17
Boxer/Staffordshire                                      10
American Staffordshire Terrier/Labrador Retriever         7
Australian Cattle Dog/Staffordshire                       7
Staffordshire/Labrador Retriever                          5
Labrador Retriever/Staffordshire                          5
Staffordshire/Boxer                                       4
Staffordshire/Beagle                                      3
American Staffordshire Terrier/American Bulldog           3
American Staffordshire Terrier/Pit Bull                   3
Boxer/American Staffordshire Terrier                      3
Staffordshire/English Bulldog                             2
American Staffordshire Terrier/Boxer                      2
Staffordshire/Blue Lacy                                   2
Staffordshire/Boston Terrier                              2
Pug/Staffordshire                                         2
Catahoula/Staffordshire                                   2
Pointer/Staffordshire                                     2
Staffordshire/Australian Cattle Dog                       2
Staffordshire/Bull Terrier                                2
American Staffordshire Terrier/Plott Hound                1
English Bulldog/American Staffordshire Terrier            1
Black Mouth Cur/American Staffordshire Terrier            1
Border Collie/Staffordshire                               1
Chinese Sharpei/American Staffordshire Terrier            1
Jack Russell Terrier/American Staffordshire Terrier       1
American Bulldog/American Staffordshire Terrier           1
Beagle/American Staffordshire Terrier                     1
American Staffordshire Terrier/Rottweiler                 1
Staffordshire/Basset Hound                                1
Cardigan Welsh Corgi/American Staffordshire Terrier       1
Beagle/Staffordshire                                      1
Australian Cattle Dog/American Staffordshire Terrier      1
Labrador Retriever/American Staffordshire Terrier         1
Rottweiler/Staffordshire                                  1
American Staffordshire Terrier/Jack Russell Terrier       1
Staffordshire/Border Collie                               1
Staffordshire/French Bulldog                              1
Staffordshire/Bulldog                                     1
Vizsla/Staffordshire                                      1
English Bulldog/Staffordshire                             1
Dachshund/American Staffordshire Terrier                  1
Border Collie/American Staffordshire Terrier              1
Great Dane/Staffordshire                                  1
American Staffordshire Terrier/Australian Cattle Dog      1
American Staffordshire Terrier/French Bulldog             1
American Staffordshire Terrier/Rhod Ridgeback             1
Black Mouth Cur/Staffordshire                             1
Name: count, dtype: int64

### Top 50 Cat Breeds

In [324]:
intakes[intakes["animal_type"] == "Cat"]["breed"].value_counts().head(50)

breed
Domestic Shorthair Mix             23519
Domestic Medium Hair Mix            2337
Domestic Longhair Mix               1254
Siamese Mix                          999
Domestic Shorthair                   387
American Shorthair Mix               213
Snowshoe Mix                         146
Domestic Medium Hair                 133
Maine Coon Mix                       104
Manx Mix                              80
Russian Blue Mix                      63
Siamese                               63
Domestic Longhair                     44
Himalayan Mix                         34
Ragdoll Mix                           23
Persian Mix                           19
Siamese/Domestic Shorthair            13
Bengal Mix                            13
Angora Mix                            12
Balinese Mix                          11
American Curl Shorthair Mix           11
Japanese Bobtail Mix                  10
Maine Coon                            10
Persian                                9
Tonkinese Mix                          8
Snowshoe                               8
Bombay Mix                             7
Cymric Mix                             6
Himalayan                              6
British Shorthair Mix                  6
Turkish Angora Mix                     5
Russian Blue                           5
Abyssinian Mix                         4
Manx/Domestic Shorthair                4
Pixiebob Shorthair Mix                 4
Norwegian Forest Cat Mix               4
Devon Rex Mix                          4
Ragdoll                                4
Sphynx                                 3
Oriental Sh Mix                        3
Cornish Rex Mix                        3
Domestic Medium Hair/Siamese           3
Siamese/Japanese Bobtail               3
American Curl Shorthair                3
Exotic Shorthair Mix                   3
Bengal                                 2
Birman Mix                             2
Domestic Medium Hair/Maine Coon        2
Domestic Longhair/Persian              2
Snowshoe/Ragdoll                       2
Name: count, dtype: int64

### Count of Unique Cat Breeds

In [325]:
intakes[intakes["animal_type"] == "Cat"]["breed"].nunique()

83

### Domestic Shorthair Breed Variations

In [326]:
intakes[intakes["breed"].str.contains("domestic shorthair", case=False, na=False)]["breed"].value_counts()

breed
Domestic Shorthair Mix                   23519
Domestic Shorthair                         387
Siamese/Domestic Shorthair                  13
Manx/Domestic Shorthair                      4
Bengal/Domestic Shorthair                    2
Domestic Shorthair/Siamese                   2
Domestic Shorthair/Manx                      1
Domestic Shorthair/Maine Coon                1
Snowshoe/Domestic Shorthair                  1
Domestic Shorthair/Abyssinian                1
Domestic Shorthair/British Shorthair         1
Scottish Fold/Domestic Shorthair             1
Domestic Shorthair/Domestic Shorthair        1
Name: count, dtype: int64

#### Verify that "Shorthair" is not written as "Short Hair" anywhere in the dataset:

In [327]:
intakes[intakes["breed"].str.contains("domestic short hair", case=False, na=False)]["breed"].value_counts()

Series([], Name: count, dtype: int64)

### Domestic Longhair Breed Variations

In [328]:
intakes[intakes["breed"].str.contains("domestic longhair", case=False, na=False)]["breed"].value_counts()

breed
Domestic Longhair Mix                  1254
Domestic Longhair                        44
Domestic Longhair/Persian                 2
Domestic Longhair/Rex                     2
Manx/Domestic Longhair                    2
Domestic Longhair/Domestic Longhair       1
Domestic Longhair/Russian Blue            1
Name: count, dtype: int64

#### Verify that "Longhair" is not written as "Long Hair" anywhere in the dataset:

In [329]:
intakes[intakes["breed"].str.contains("domestic long hair", case=False, na=False)]["breed"].value_counts()

Series([], Name: count, dtype: int64)

### Domestic Medium Hair Breed Variations

In [330]:
intakes[intakes["breed"].str.contains("domestic medium hair", case=False, na=False)]["breed"].value_counts()

breed
Domestic Medium Hair Mix           2337
Domestic Medium Hair                133
Domestic Medium Hair/Siamese          3
Domestic Medium Hair/Maine Coon       2
Domestic Medium Hair/Manx             1
Name: count, dtype: int64

#### Verify that "Medium Hair" is not written as "Mediumhair" anywhere in the dataset:

In [331]:
intakes[intakes["breed"].str.contains("domestic mediumhair", case=False, na=False)]["breed"].value_counts()

Series([], Name: count, dtype: int64)

### Investigating Breed Name Abbreviations

#### Verifying that there are no other breed name abbreviations aside from "Oriental Sh":

In [332]:
intakes[intakes["breed"].str.contains(" sh ", case=False, na=False)]["breed"].value_counts()

breed
Rabbit Sh Mix      294
Oriental Sh Mix      3
Name: count, dtype: int64

#### <a id="oriental-sh-mix"></a>Verifying that there are only "Oriental Sh Mix" instances:

In [333]:
intakes[intakes["breed"].str.contains("oriental", case=False, na=False)]["breed"].value_counts()

breed
Oriental Sh Mix    3
Name: count, dtype: int64

In [334]:
pd.reset_option("display.max_rows")

### <a id="datetime"></a>Verifying the Similarity of the `datetime` and `datetime2` columns

#### Checking if every row is identical:

In [335]:
(intakes["datetime"] == intakes["datetime2"]).all()

True

#### Counting the differences in `datetime` and `datetime2` values for each row

In [336]:
(intakes["datetime"] != intakes["datetime2"]).sum()

0

### Profiling the `age_upon_intake` column

In [337]:
intakes["age_upon_intake"].value_counts().head(30)

age_upon_intake
1 year       14672
2 years      11617
1 month       7468
3 years       5250
2 months      4027
4 years       3102
4 weeks       2827
5 years       2755
3 weeks       2286
4 months      2049
5 months      2009
3 months      1938
6 years       1869
2 weeks       1599
7 years       1596
6 months      1546
8 years       1542
9 months      1197
10 years      1174
7 months      1156
8 months       903
9 years        878
10 months      714
1 week         668
12 years       595
1 weeks        528
11 months      527
0 years        456
11 years       454
13 years       380
Name: count, dtype: int64

In [338]:
intakes[intakes["age_upon_intake"].str.contains("days|day", case=False, na=False)]["age_upon_intake"].value_counts()

age_upon_intake
3 days    375
1 day     349
2 days    271
4 days    199
6 days    190
5 days    125
Name: count, dtype: int64


## Outcomes
### Column Info

In [339]:
outcomes.info()

<class 'pandas.DataFrame'>
RangeIndex: 80681 entries, 0 to 80680
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age_upon_outcome  80673 non-null  str
 1   animal_id         80681 non-null  str
 2   animal_type       80681 non-null  str
 3   breed             80681 non-null  str
 4   color             80681 non-null  str
 5   date_of_birth     80681 non-null  str
 6   datetime          80681 non-null  str
 7   monthyear         80681 non-null  str
 8   name              56116 non-null  str
 9   outcome_subtype   36893 non-null  str
 10  outcome_type      80667 non-null  str
 11  sex_upon_outcome  80679 non-null  str
dtypes: str(12)
memory usage: 7.4 MB

### Descriptive Statistics

In [340]:
outcomes.describe()

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
count,80673,80681,80681,80681,80681,80681,80681,80681,56116,36893,80667,80679
unique,46,72877,5,2176,532,5956,66474,66474,14824,19,9,5
top,1 year,A721033,Dog,Domestic Shorthair Mix,Black/White,2014-05-05T00:00:00,2016-04-18T00:00:00,2016-04-18T00:00:00,Bella,Partner,Adoption,Neutered Male
freq,14911,13,45856,23821,8396,112,39,39,362,20082,34232,28702

### Missing Values

In [341]:
outcomes.isnull().sum()

age_upon_outcome        8
animal_id               0
animal_type             0
breed                   0
color                   0
date_of_birth           0
datetime                0
monthyear               0
name                24565
outcome_subtype     43788
outcome_type           14
sex_upon_outcome        2
dtype: int64

### Duplicate Rows

In [342]:
outcomes.duplicated().sum()

10

### <a id="outcomes-breeds"></a>Breed Distribution

In [343]:
outcomes["breed"].value_counts()

breed
Domestic Shorthair Mix          23821
Pit Bull Mix                     6361
Chihuahua Shorthair Mix          4874
Labrador Retriever Mix           4849
Domestic Medium Hair Mix         2368
                                ...
Guinea                              1
Norfolk Terrier/Pug                 1
Pomeranian/Beagle                   1
Chickadee Mix                       1
Labrador Retriever/Pekingese        1
Name: count, Length: 2176, dtype: int64

### Outcome Type Distribution

In [344]:
outcomes["outcome_type"].value_counts()

outcome_type
Adoption           34232
Transfer           24050
Return to Owner    14851
Euthanasia          6289
Died                 699
Disposal             304
Rto-Adopt            179
Missing               47
Relocate              16
Name: count, dtype: int64

### Animal Type Distribution

In [345]:
outcomes["animal_type"].value_counts()

animal_type
Dog          45856
Cat          30028
Other         4446
Bird           341
Livestock       10
Name: count, dtype: int64

### Profiling the `age_upon_outcome` column

In [346]:
outcomes["age_upon_outcome"].value_counts().head(30)

age_upon_outcome
1 year       14911
2 years      11683
2 months      9377
3 years       5326
3 months      3481
1 month       3424
4 years       3092
5 years       2789
4 months      2470
5 months      1995
6 months      1940
6 years       1878
8 years       1608
7 years       1588
3 weeks       1474
2 weeks       1348
10 months     1241
8 months      1221
4 weeks       1206
10 years      1205
7 months      1001
9 years        855
9 months       718
12 years       619
1 weeks        528
11 months      520
11 years       447
1 week         429
13 years       403
14 years       260
Name: count, dtype: int64

In [347]:
outcomes[outcomes["age_upon_outcome"].str.contains("days|day", case=False, na=False)]["age_upon_outcome"].value_counts()

age_upon_outcome
3 days    239
2 days    226
1 day     157
6 days    153
4 days    140
5 days    116
Name: count, dtype: int64

### Profiling the `outcome_type` column

In [348]:
outcomes["outcome_type"].value_counts()

outcome_type
Adoption           34232
Transfer           24050
Return to Owner    14851
Euthanasia          6289
Died                 699
Disposal             304
Rto-Adopt            179
Missing               47
Relocate              16
Name: count, dtype: int64

### <a id="outcome-subtypes"></a>Profiling the `outcome_subtype` column

In [349]:
outcomes["outcome_subtype"].value_counts()

outcome_subtype
Partner                20082
Foster                  5714
SCRP                    3211
Suffering               2563
Rabies Risk             2546
Snr                      755
Aggressive               508
Offsite                  367
In Kennel                354
Medical                  268
In Foster                183
Behavior                 142
At Vet                    71
Enroute                   49
Underage                  28
Court/Investigation       23
In Surgery                17
Possible Theft             9
Barn                       3
Name: count, dtype: int64

## <a id="intakes-vs-outcomes"></a>Comparing Intakes & Outcomes

### Breeds in the Outcomes Dataset That Are Not in the Intakes Dataset

In [350]:
outcomes[~outcomes["breed"].isin(intakes["breed"])]["breed"].value_counts()

breed
Cold Water Mix                                      2
Manchester Terrier                                  1
Chinese Sharpei/Bull Terrier                        1
Beagle/Border Terrier                               1
Bull Terrier/Border Collie                          1
Border Terrier/Miniature Schnauzer                  1
Pointer/Chinese Sharpei                             1
Domestic Shorthair/Domestic Medium Hair             1
Akita/Chow Chow                                     1
Pit Bull/Border Terrier                             1
Hovawart Mix                                        1
Dogue De Bordeaux/Labrador Retriever                1
Miniature                                           1
Doberman Pinsch/Catahoula                           1
Nova Scotia Duck Tolling Retriever/Border Collie    1
Chickadee Mix                                       1
Labrador Retriever/Pekingese                        1
Name: count, dtype: int64

### Breeds in the Intakes Dataset That Are Not in the Outcomes Dataset

In [351]:
intakes[~intakes["breed"].isin(outcomes["breed"])]["breed"].value_counts()

breed
Chihuahua Longhair/Silky Terrier          1
German Shorthair Pointer/Border Collie    1
Doberman Pinsch/Greyhound                 1
Toy Poodle/Chihuahua Shorthair            1
German Shepherd/Bloodhound                1
Pointer/Beagle                            1
Siamese/Snowshoe                          1
Name: count, dtype: int64


## Key Findings

### Common Values

* The most common dog breed at the shelter is a Pit Bull Mix (seen in both [intakes](#intakes-breeds) and [outcomes](#outcomes-breeds)).
* The most common cat breed at the shelter is a Domestic Shorthair Mix (seen in both [intakes](#intakes-breeds) and [outcomes](#outcomes-breeds)).
    * It is worth noting that this is a very generalized breed which does not take into account cat color (which prospective adopters may factor into their decision to adopt). Thus, animal breed and color may need to be considered together for accurate analysis.
* The majority of animals at the shelter are dogs, followed by cats.
  
### What to Fix

* Standardize `breed` values for cats and dogs. Upon comparing `breed` values for `intakes` vs. `outcomes`, I concluded that the same standardization rules apply to both datasets ([see here](#intakes-vs-outcomes)).
    * Standardize `breed` values for cross-breeds as `Mix` (e.g. `Pug/Chihuahua` becomes `Pug Mix`).
    * Standardize `breed` value `American Pit Bull Terrier` to `Pit Bull`.
    * Standardize `breed` value `Queensland Heeler` to `Australian Cattle Dog`. These are the same dog breed, with the more common naming being `Australian Cattle Dog` ([see here](#Top-50-Dog-Breeds)).
    * Standardize `breed` value `Oriental Sh Mix` to `Oriental Shorthair Mix`.
        * I confirmed that there are only instances of `Oriental Sh Mix`, no purebreds ([see here](#oriental-sh-mix)).
* `datetime`, `datetime2`, `date_of_birth`, and `monthyear` are stored as `str` type instead of `datetime` type.
    * `datetime` will be converted 
* There is a large amount of null `name` values that need to be handled.
* `age_upon_intake` and `age_upon_outcome` are currently stored as `str` type and require parsing.
  
### Other Notes

* There are similarly named `breed` values `Staffordshire` and `American Staffordshire Terrier` ([see here](#Staffordshire-Breed-Variations)). I left the ambiguous `Staffordshire` breed entries unchanged because I couldn't confirm the intended breed without additional context (`Staffordshire` could refer to the `Staffordshire Bull Terrier` or the `American Staffordshire Terrier`, two distinct breeds).
* Upon profiling the `outcome_subtype` column ([see here](#outcome-subtypes)), I noted a few abbreviations, namely `Snr` (most likely meaning `Shelter-Neuter-Release`) and `SCRP` (most likely meaning `Stray Cat Return Program`). However, I left these ambiguous entries unchanged because I could not confirm their meaning without additional context. This is not of concern, as `outcome_subtype` will not be heavily used during gold layer analytics, which will rely moreso on the generalized `outcome_type`.