In [19]:
import duckdb
import pandas as pd

con = duckdb.connect("../data/shelterflow.duckdb")
bronze_intakes = con.execute("SELECT * FROM bronze_intakes").df()
bronze_outcomes = con.execute("SELECT * FROM bronze_outcomes").df()
silver_intakes = con.execute("SELECT * FROM silver_intakes").df()
silver_outcomes = con.execute("SELECT * FROM silver_outcomes").df()

pd.set_option("display.max_rows", None)

# `silver_intakes` Validation

In [20]:
silver_intakes.info()

<class 'pandas.DataFrame'>
RangeIndex: 80159 entries, 0 to 80158
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   animal_id           80159 non-null  str
 1   animal_type         80159 non-null  str
 2   intake_type         80159 non-null  str
 3   intake_condition    80159 non-null  str
 4   sex_upon_intake     80158 non-null  str
 5   age_upon_intake     80159 non-null  str
 6   found_location      80159 non-null  str
 7   color               80159 non-null  str
 8   name                55585 non-null  str
 9   breed               80159 non-null  str
 10  breed_standardized  80159 non-null  str
 11  age_in_days         80159 non-null  int32
 12  age_group           75379 non-null  str
 13  intake_date         80159 non-null  datetime64[us]
dtypes: datetime64[us](1), int32(1), str(12)
memory usage: 8.3 MB

## Comparing `silver_intakes` against `bronze_intakes`

In [21]:
silver_intakes.head(30)

,animal_id,animal_type,intake_type,intake_condition,sex_upon_intake,age_upon_intake,found_location,color,name,breed,breed_standardized,age_in_days,age_group,intake_date
0,A731435,Cat,Owner Surrender,Normal,Neutered Male,5 months,Austin (TX),Cream Tabby,*Casey,Domestic Shorthair Mix,Domestic Shorthair Mix,150,Kitten,2016-08-08
1,A758038,Dog,Stray,Normal,Intact Female,1 year,7100 Colony Park Drive in Austin (TX),Black/White,NaN,Siberian Husky Mix,Siberian Husky Mix,365,Young,2017-09-10
2,A746979,Dog,Owner Surrender,Normal,Intact Male,1 year,7601 Daffan Ln in Austin (TX),Brown Brindle,Teddy,Chihuahua Shorthair Mix,Chihuahua Shorthair Mix,365,Young,2017-04-12
3,A705868,Dog,Stray,Normal,Intact Male,5 months,22009 Hogeye Rd in Austin (TX),Red,Izzy,Golden Retriever Mix,Golden Retriever Mix,150,Puppy,2015-06-22
4,A714106,Dog,Stray,Normal,Intact Male,1 year,183/Mlk in Travis (TX),White/Brown,*Nexus,Pit Bull Mix,Pit Bull Mix,365,Young,2015-10-18
5,A717905,Dog,Stray,Normal,Intact Male,1 month,11717 Schriber Rd in Travis (TX),Black,NaN,Chesa Bay Retr Mix,Chesa Bay Retr Mix,30,Puppy,2015-12-17
6,A675336,Dog,Stray,Normal,Intact Female,3 years,Iwanna Dr in Del Valle (TX),Silver,Runt Runt,Standard Schnauzer Mix,Standard Schnauzer Mix,1095,Adult,2014-03-26
7,A726125,Dog,Owner Surrender,Normal,Spayed Female,1 year,Austin (TX),Brown,Carley,Pit Bull Mix,Pit Bull Mix,365,Young,2017-04-07
8,A739497,Dog,Stray,Normal,Intact Female,2 years,1515 Wickersham Ln in Austin (TX),Brown,*Millie,Australian Cattle Dog/Beagle,Australian Cattle Dog Mix,730,Young,2016-12-03
9,A734336,Other,Wildlife,Sick,Unknown,1 year,245 W 3Rd St in Austin (TX),Brown,NaN,Rat,Rat,365,NaN,2016-09-05
10,A679273,Cat,Stray,Normal,Intact Male,1 month,9607 Hansford Dr in Austin (TX),Orange Tabby,*Marmalade,Domestic Shorthair Mix,Domestic Shorthair Mix,30,Kitten,2014-05-18
11,A672005,Dog,Owner Surrender,Normal,Intact Female,1 year,Austin (TX),Chocolate/White,Hazel,Labrador Retriever/Pointer,Labrador Retriever Mix,365,Young,2014-02-02
12,A697897,Cat,Stray,Injured,Intact Male,3 years,6913 Whispering Oaks in Austin (TX),Brown Tabby,NaN,Domestic Longhair Mix,Domestic Longhair Mix,1095,Adult,2015-03-03
13,A723084,Other,Wildlife,Sick,Unknown,2 years,1605 Suffolk Dr in Austin (TX),Black/White,NaN,Raccoon Mix,Raccoon Mix,730,NaN,2016-03-26
14,A721380,Dog,Stray,Normal,Intact Male,5 years,Virgo Ln And in Austin (TX),Blue/White,*Leo,Pit Bull Mix,Pit Bull Mix,1825,Adult,2016-02-25
15,A747288,Cat,Stray,Normal,Intact Female,1 year,10610 Morado Cir in Austin (TX),Black,NaN,Domestic Shorthair Mix,Domestic Shorthair Mix,365,Young,2017-04-17
16,A723523,Cat,Stray,Normal,Neutered Male,3 years,5305 Park At Woodlands in Austin (TX),White,*Hollywood,Angora Mix,Angora Mix,1095,Adult,2016-04-02
17,A728886,Dog,Stray,Normal,Intact Male,8 months,1120 Brookswood Ave in Austin (TX),Blue/White,Pretty Boy,Pit Bull Mix,Pit Bull Mix,240,Puppy,2016-06-09
18,A650538,Dog,Stray,Normal,Intact Male,2 years,615 Thrasher in Austin (TX),Black/Tan,Negrito,Chihuahua Shorthair Mix,Chihuahua Shorthair Mix,730,Young,2015-02-10
19,A726971,Cat,Stray,Normal,Intact Male,1 month,9300 S Ih 35 Frontage Rd in Austin (TX),Black/White,*Duke,Domestic Shorthair Mix,Domestic Shorthair Mix,30,Kitten,2016-05-17
20,A707196,Dog,Stray,Normal,Neutered Male,12 years,Little Pebble Dr And Metric in Austin (TX),White/Black,*Frank,Jack Russell Terrier Mix,Jack Russell Terrier Mix,4380,Senior,2015-07-09
21,A689063,Dog,Owner Surrender,Normal,Intact Female,1 month,Travis (TX),Blue/White,NaN,Flat Coat Retriever/Pit Bull,Flat Coat Retriever Mix,30,Puppy,2014-09-28
22,A680929,Dog,Stray,Injured,Spayed Female,3 years,12034 Research in Austin (TX),White,*Elsa,Great Pyrenees Mix,Great Pyrenees Mix,1095,Adult,2014-06-10
23,A678011,Dog,Stray,Normal,Neutered Male,2 years,Teri And Copperbend in Austin (TX),Gray/White,Rhino,Pit Bull Mix,Pit Bull Mix,730,Young,2015-01-15
24,A764851,Cat,Stray,Normal,Intact Male,2 months,Austin (TX),Brown Tabby,NaN,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2018-01-07
25,A733153,Cat,Stray,Normal,Intact Female,1 month,2300 W Northloop Blvd in Austin (TX),Black,Scarlett,Domestic Longhair Mix,Domestic Longhair Mix,30,Kitten,2016-08-18
26,A754224,Cat,Owner Surrender,Normal,Spayed Female,6 years,Austin (TX),White,Suchen,Domestic Shorthair Mix,Domestic Shorthair Mix,2190,Adult,2017-07-17
27,A760583,Dog,Owner Surrender,Injured,Intact Female,10 months,Austin (TX),Tan,Layla,Chihuahua Shorthair Mix,Chihuahua Shorthair Mix,300,Puppy,2017-10-20
28,A765830,Cat,Stray,Normal,Intact Female,2 months,2503 East Oltorf in Austin (TX),Tortie,NaN,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2018-01-28
29,A665334,Dog,Public Assist,Normal,Neutered Male,5 years,6315 Ken Caryl Dr in Austin (TX),Blue/White,Mcruber,Pit Bull Mix,Pit Bull Mix,1825,Adult,2017-07-06

In [22]:
bronze_intakes.head(30)

,age_upon_intake,animal_id,animal_type,breed,color,datetime,datetime2,found_location,intake_condition,intake_type,name,sex_upon_intake
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,Belle,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,Runster,Intact Male
2,4 weeks,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T07:59:00.000,Austin (TX),Sick,Stray,NaN,Intact Female
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,Rio,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,Odin,Neutered Male
5,2 years,A708452,Dog,Labrador Retriever Mix,Black/White,2015-07-30T14:37:00.000,2015-07-30T14:37:00.000,Austin (TX),Normal,Public Assist,Mumble,Intact Male
6,5 months,A731435,Cat,Domestic Shorthair Mix,Cream Tabby,2016-08-08T17:52:00.000,2016-08-08T17:52:00.000,Austin (TX),Normal,Owner Surrender,*Casey,Neutered Male
7,2 years,A760053,Dog,Chihuahua Shorthair,White/Tan,2017-10-11T15:46:00.000,2017-10-11T15:46:00.000,8800 South First Street in Austin (TX),Normal,Stray,NaN,Intact Male
8,5 months,A707375,Dog,Pit Bull,Brown/White,2015-07-11T18:19:00.000,2015-07-11T18:19:00.000,Galilee Court And Damita Jo Dr in Manor (TX),Normal,Stray,*Candy Cane,Intact Female
9,2 years,A696408,Dog,Chihuahua Shorthair,Tricolor,2015-02-04T12:58:00.000,2015-02-04T12:58:00.000,9705 Thaxton in Austin (TX),Normal,Stray,*Pearl,Intact Female
10,2 years,A743114,Cat,Domestic Shorthair Mix,Black/White,2017-02-04T10:10:00.000,2017-02-04T10:10:00.000,208 Beaver St in Austin (TX),Injured,Stray,NaN,Intact Female
11,14 years,A657188,Cat,Domestic Shorthair Mix,Brown Tabby/White,2013-11-10T17:19:00.000,2013-11-10T17:19:00.000,Austin (TX),Normal,Owner Surrender,Tommy,Neutered Male
12,4 weeks,A707658,Cat,Domestic Shorthair Mix,Black/White,2015-07-15T17:43:00.000,2015-07-15T17:43:00.000,6118 Fairway in Austin (TX),Normal,Stray,*Mint,Intact Female
13,1 month,A736287,Cat,Domestic Shorthair Mix,Torbie,2016-10-08T11:53:00.000,2016-10-08T11:53:00.000,South First And Stassney in Austin (TX),Normal,Stray,*Twilight,Intact Female
14,2 months,A697950,Dog,Australian Cattle Dog/Labrador Retriever,Tan/White,2015-03-04T11:22:00.000,2015-03-04T11:22:00.000,1501 S Fm 973 in Austin (TX),Normal,Stray,NaN,Intact Female
15,18 years,A298074,Dog,Parson Russell Terrier Mix,Black/White,2015-09-06T14:21:00.000,2015-09-06T14:21:00.000,1801 Westridge in Austin (TX),Normal,Stray,Stumpy,Spayed Female
16,2 years,A707974,Cat,Domestic Shorthair Mix,Blue,2015-07-20T18:13:00.000,2015-07-20T18:13:00.000,2307 Ventura in Austin (TX),Normal,Stray,*Cleopatra,Intact Female
17,5 months,A682230,Dog,Maltese Mix,White,2014-06-25T16:27:00.000,2014-06-25T16:27:00.000,3737 Keats Dr in Austin (TX),Normal,Stray,NaN,Intact Female
18,4 months,A749436,Dog,Dachshund Mix,Brown/White,2017-05-15T09:50:00.000,2017-05-15T09:50:00.000,East Pleasant Valley And Stassney in Austin (TX),Normal,Stray,NaN,Intact Male
19,1 year,A722979,Other,Bat Mix,Brown,2016-03-24T16:39:00.000,2016-03-24T16:39:00.000,4100 Westbank Dr in Austin (TX),Normal,Wildlife,NaN,Unknown
20,2 years,A696205,Cat,Domestic Shorthair Mix,Black,2015-02-12T11:57:00.000,2015-02-12T11:57:00.000,Austin (TX),Normal,Owner Surrender,Roo,Spayed Female
21,1 month,A759935,Dog,Labrador Retriever Mix,Black,2017-10-09T22:39:00.000,2017-10-09T22:39:00.000,4800 Cottonwood St in Austin (TX),Normal,Stray,Dieve,Intact Female
22,1 year,A666877,Dog,Dachshund Mix,Tan/White,2013-11-08T15:24:00.000,2013-11-08T15:24:00.000,Guadalupe/St. Johns in Austin (TX),Normal,Stray,*Romeo,Intact Male
23,4 days,A706507,Cat,Domestic Shorthair Mix,Black,2015-06-29T17:04:00.000,2015-06-29T17:04:00.000,5306 Peppertree in Austin (TX),Normal,Stray,NaN,Unknown
24,2 months,A732903,Dog,Labrador Retriever Mix,Black/White,2016-08-14T15:02:00.000,2016-08-14T15:02:00.000,Austin (TX),Injured,Stray,*Raven,Intact Female
25,1 day,A749400,Cat,Domestic Shorthair Mix,Blue,2017-05-14T14:19:00.000,2017-05-14T14:19:00.000,1834 Ferguson in Austin (TX),Normal,Stray,*Pepper,Intact Female
26,2 years,A727838,Cat,Domestic Shorthair Mix,Black,2016-05-26T14:01:00.000,2016-05-26T14:01:00.000,2504 Huntwick Dr in Austin (TX),Normal,Stray,NaN,Intact Female
27,2 weeks,A701811,Cat,Domestic Shorthair Mix,Gray Tabby,2015-05-05T07:29:00.000,2015-05-05T07:29:00.000,4434 Frontier Trl in Austin (TX),Nursing,Stray,NaN,Unknown
28,3 years,A700396,Dog,Pit Bull Mix,Black/White,2015-12-07T09:11:00.000,2015-12-07T09:11:00.000,4200 Smith School Rd in Austin (TX),Normal,Stray,Calseta,Spayed Female
29,4 years,A724378,Dog,Tibetan Spaniel Mix,Black/White,2016-04-16T13:36:00.000,2016-04-16T13:36:00.000,Austin (TX),Normal,Owner Surrender,Boxer,Intact Male

## Verifying `age_group` populates sensibly

In [23]:
silver_intakes[["age_upon_intake", "age_group"]].value_counts().reset_index(name="count")

   age_upon_intake age_group  count
0           1 year     Young  12433
1          2 years     Young  10762
2          3 years     Adult   4983
3          1 month    Kitten   4962
4          4 years     Adult   3025
5          5 years     Adult   2720
6          1 month     Puppy   2468
7          4 weeks    Kitten   2210
8          3 weeks    Kitten   2128
9         2 months    Kitten   2066
10        2 months     Puppy   1915
11         6 years     Adult   1862
12         7 years     Adult   1590
13         8 years    Senior   1535
14         2 weeks    Kitten   1433
15        10 years    Senior   1171
16        4 months     Puppy   1138
17        5 months     Puppy   1095
18        3 months    Kitten   1032
19        9 months     Puppy    913
20         9 years    Senior    876
21        3 months     Puppy    870
22        4 months    Kitten    864
23        6 months     Puppy    829
24        7 months     Puppy    807
25        8 months     Puppy    638
26        5 months    Kitten    606
27        12 years    Senior    594
28       10 months     Puppy    549
29          1 week    Kitten    519
30        6 months    Kitten    488
31        11 years    Senior    454
32       11 months     Puppy    448
33         1 weeks    Kitten    432
34        13 years    Senior    379
35        7 months    Kitten    318
36         4 weeks     Puppy    301
37          3 days    Kitten    286
38        9 months    Kitten    257
39        14 years    Senior    250
40        8 months    Kitten    240
41        15 years    Senior    213
42         0 years    Kitten    212
43          2 days    Kitten    212
44           1 day    Kitten    207
45         0 years     Puppy    202
46       10 months    Kitten    155
47          6 days    Kitten    148
48          1 week     Puppy    144
49         3 weeks     Puppy    143
50         5 weeks    Kitten    139
51           1 day     Puppy    129
52         2 weeks     Puppy    115
53          4 days    Kitten    112
54        16 years    Senior    108
55          3 days     Puppy     83
56          5 days    Kitten     82
57         1 weeks     Puppy     79
58          4 days     Puppy     72
59       11 months    Kitten     71
60         5 weeks     Puppy     64
61        17 years    Senior     59
62          2 days     Puppy     58
63          5 days     Puppy     36
64          6 days     Puppy     35
65        18 years    Senior     26
66        19 years    Senior     13
67        20 years    Senior     12
68        22 years    Senior      4

In [24]:
silver_intakes[(silver_intakes["animal_type"].isin(["Dog", "Cat"])) & (silver_intakes["age_group"].isnull())].shape[0]

0

## Verifying deduplication

In [25]:
silver_intakes.duplicated().sum()

0

# `silver_outcomes` Validation

In [26]:
silver_outcomes.info()

<class 'pandas.DataFrame'>
RangeIndex: 80658 entries, 0 to 80657
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   animal_id           80658 non-null  str
 1   animal_type         80658 non-null  str
 2   outcome_type        80644 non-null  str
 3   outcome_subtype     36886 non-null  str
 4   sex_upon_outcome    80656 non-null  str
 5   age_upon_outcome    80650 non-null  str
 6   name                56101 non-null  str
 7   color               80658 non-null  str
 8   breed               80658 non-null  str
 9   breed_standardized  80658 non-null  str
 10  age_in_days         80650 non-null  Int32
 11  age_group           75856 non-null  str
 12  outcome_date        80658 non-null  datetime64[us]
 13  date_of_birth       80658 non-null  datetime64[us]
dtypes: Int32(1), datetime64[us](2), str(11)
memory usage: 8.4 MB

In [27]:
silver_outcomes.head(30)

,animal_id,animal_type,outcome_type,outcome_subtype,sex_upon_outcome,age_upon_outcome,name,color,breed,breed_standardized,age_in_days,age_group,outcome_date,date_of_birth
0,A661023,Dog,Adoption,Foster,Neutered Male,3 years,Lucky,White,Miniature Poodle Mix,Miniature Poodle Mix,1095,Adult,2013-10-15,2010-08-15
1,A677147,Dog,Return to Owner,NaN,Spayed Female,9 years,Joy,White/Tan,Beagle Mix,Beagle Mix,3285,Senior,2014-04-20,2005-04-20
2,A682239,Cat,Adoption,Foster,Spayed Female,2 months,*Rust,Tortie,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2014-08-03,2014-05-25
3,A682584,Dog,Adoption,NaN,Neutered Male,1 year,NaN,Tan/White,Chihuahua Shorthair Mix,Chihuahua Shorthair Mix,365,Young,2014-07-13,2013-06-30
4,A669279,Dog,Adoption,NaN,Neutered Male,10 months,Sagan,Tricolor,Anatol Shepherd Mix,Anatol Shepherd Mix,300,Puppy,2013-12-24,2013-02-17
5,A665982,Dog,Return to Owner,NaN,Spayed Female,5 years,Minnie,White/Tan,Chihuahua Shorthair/Cardigan Welsh Corgi,Chihuahua Shorthair Mix,1825,Adult,2013-10-26,2008-10-25
6,A675669,Dog,Adoption,NaN,Spayed Female,1 year,NaN,Blue Merle/Tan,Queensland Heeler Mix,Australian Cattle Dog Mix,365,Young,2014-04-06,2013-03-31
7,A679717,Cat,Transfer,Partner,Intact Female,3 weeks,NaN,Torbie,Domestic Shorthair Mix,Domestic Shorthair Mix,21,Kitten,2014-05-25,2014-05-03
8,A682002,Cat,Transfer,Partner,Intact Female,2 days,NaN,Calico,Domestic Shorthair Mix,Domestic Shorthair Mix,2,Kitten,2014-06-22,2014-06-20
9,A669791,Cat,Transfer,SCRP,Intact Female,1 year,NaN,Tortie,Domestic Shorthair Mix,Domestic Shorthair Mix,365,Young,2013-12-28,2012-12-27
10,A678398,Dog,Euthanasia,Suffering,Intact Female,10 years,Unique,Black/Tan,Rottweiler Mix,Rottweiler Mix,3650,Senior,2014-05-08,2004-05-08
11,A622128,Dog,Adoption,NaN,Spayed Female,1 year,Ginger,Brown Brindle/White,Boxer Mix,Boxer Mix,365,Young,2014-01-19,2012-02-09
12,A667798,Dog,Transfer,Partner,Neutered Male,3 years,Henry Jones,White/White,Shih Tzu Mix,Shih Tzu Mix,1095,Adult,2013-11-23,2010-11-23
13,A675411,Other,Euthanasia,Rabies Risk,Unknown,1 year,NaN,Brown,Bat Mix,Bat Mix,365,NaN,2014-03-27,2013-03-27
14,A682667,Dog,Adoption,NaN,Neutered Male,2 years,NaN,Black/White,Cairn Terrier/Miniature Schnauzer,Cairn Terrier Mix,730,Young,2014-07-06,2012-01-01
15,A510475,Dog,Return to Owner,NaN,Neutered Male,7 years,Duke,Red/White,Pit Bull Mix,Pit Bull Mix,2555,Adult,2014-07-04,2006-11-27
16,A674461,Dog,Transfer,Partner,Intact Male,5 days,NaN,Sable/White,Pit Bull Mix,Pit Bull Mix,5,Puppy,2014-03-13,2014-03-08
17,A668421,Dog,Euthanasia,Aggressive,Neutered Male,2 years,Babaloo,Brown/White,American Bulldog Mix,American Bulldog Mix,730,Young,2013-12-11,2011-12-03
18,A686629,Dog,Adoption,NaN,Spayed Female,2 months,Dot,White/Black,Border Collie Mix,Border Collie Mix,60,Puppy,2014-08-25,2014-06-18
19,A669640,Dog,Return to Owner,NaN,Intact Female,8 months,Sissy,Brown/White,Australian Kelpie Mix,Australian Kelpie Mix,240,Puppy,2014-01-03,2013-04-25
20,A651452,Dog,Adoption,Foster,Neutered Male,1 year,*Kenny,Black/White,Border Collie/Labrador Retriever,Border Collie Mix,365,Young,2013-11-09,2012-04-10
21,A675190,Other,Euthanasia,Suffering,Unknown,4 days,NaN,Pink,Opossum Mix,Opossum Mix,4,NaN,2014-03-24,2014-03-20
22,A670564,Dog,Adoption,NaN,Neutered Male,2 years,*Marty,Brown Brindle,Australian Cattle Dog Mix,Australian Cattle Dog Mix,730,Young,2014-04-20,2012-01-10
23,A677836,Cat,Adoption,Foster,Spayed Female,3 months,NaN,Black/White,Domestic Shorthair Mix,Domestic Shorthair Mix,90,Kitten,2014-07-12,2014-03-29
24,A668562,Cat,Adoption,NaN,Intact Female,2 months,Prof Butters,Orange Tabby,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2013-12-13,2013-10-05
25,A681616,Dog,Adoption,NaN,Spayed Female,10 months,NaN,White/Brown Brindle,Chihuahua Shorthair Mix,Chihuahua Shorthair Mix,300,Puppy,2014-06-23,2013-08-18
26,A662820,Cat,Adoption,NaN,Spayed Female,2 months,*Indigo,Black,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2013-10-04,2013-07-18
27,A668896,Cat,Return to Owner,NaN,Spayed Female,1 year,Sofie,Black/White,Domestic Shorthair Mix,Domestic Shorthair Mix,365,Young,2013-12-11,2012-07-11
28,A682562,Dog,Adoption,NaN,Neutered Male,1 year,*Tex,Tan/White,Blue Lacy Mix,Blue Lacy Mix,365,Young,2014-07-12,2013-06-29
29,A341599,Cat,Transfer,Partner,Neutered Male,9 years,Reece,Black,Domestic Shorthair Mix,Domestic Shorthair Mix,3285,Senior,2014-01-11,2004-01-18

In [28]:
bronze_outcomes.head(30)

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,A684346,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-07T00:00:00,2014-07-22T16:04:00,2014-07-22T16:04:00,NaN,Partner,Transfer,Intact Male
1,1 year,A666430,Dog,Beagle Mix,White/Brown,2012-11-06T00:00:00,2013-11-07T11:47:00,2013-11-07T11:47:00,Lucy,Partner,Transfer,Spayed Female
2,1 year,A675708,Dog,Pit Bull,Blue/White,2013-03-31T00:00:00,2014-06-03T14:20:00,2014-06-03T14:20:00,*Johnny,NaN,Adoption,Neutered Male
3,9 years,A680386,Dog,Miniature Schnauzer Mix,White,2005-06-02T00:00:00,2014-06-15T15:50:00,2014-06-15T15:50:00,Monday,Partner,Transfer,Neutered Male
4,5 months,A683115,Other,Bat Mix,Brown,2014-01-07T00:00:00,2014-07-07T14:04:00,2014-07-07T14:04:00,NaN,Rabies Risk,Euthanasia,Unknown
5,4 months,A664462,Dog,Leonberger Mix,Brown/White,2013-06-03T00:00:00,2013-10-07T13:06:00,2013-10-07T13:06:00,*Edgar,Partner,Transfer,Intact Male
6,1 month,A685067,Cat,Domestic Shorthair Mix,Blue Tabby/White,2014-06-16T00:00:00,2014-08-14T18:45:00,2014-08-14T18:45:00,Lucy,NaN,Adoption,Intact Female
7,3 months,A678580,Cat,Domestic Shorthair Mix,White/Black,2014-03-26T00:00:00,2014-06-29T17:45:00,2014-06-29T17:45:00,*Frida,Offsite,Adoption,Spayed Female
8,1 year,A675405,Cat,Domestic Medium Hair Mix,Black/White,2013-03-27T00:00:00,2014-03-28T14:55:00,2014-03-28T14:55:00,Stella Luna,NaN,Return to Owner,Spayed Female
9,2 years,A673652,Dog,Papillon/Border Collie,Black/White,2012-02-28T00:00:00,2014-03-28T14:39:00,2014-03-28T14:39:00,Fancy,Partner,Transfer,Neutered Male
10,2 months,A677679,Dog,Chihuahua Shorthair/Pomeranian,Black,2014-03-07T00:00:00,2014-05-26T19:10:00,2014-05-26T19:10:00,Kash,Foster,Adoption,Neutered Male
11,4 years,A640655,Dog,Miniature Schnauzer/Miniature Poodle,White,2009-04-27T00:00:00,2014-04-25T11:17:00,2014-04-25T11:17:00,Sandy,NaN,Return to Owner,Spayed Female
12,2 years,A680396,Dog,Rat Terrier Mix,White/Black,2012-06-02T00:00:00,2014-06-15T15:11:00,2014-06-15T15:11:00,*Truman,Partner,Transfer,Neutered Male
13,1 year,A674298,Dog,Pit Bull Mix,Brown Brindle/White,2013-03-11T00:00:00,2014-04-16T12:51:00,2014-04-16T12:51:00,*Newt,Partner,Transfer,Neutered Male
14,3 weeks,A670420,Cat,Domestic Shorthair Mix,Black/White,2013-12-16T00:00:00,2014-01-09T19:29:00,2014-01-09T19:29:00,NaN,Partner,Transfer,Intact Male
15,2 months,A684460,Cat,Domestic Shorthair Mix,Brown Tabby,2014-06-02T00:00:00,2014-08-13T15:04:00,2014-08-13T15:04:00,Elsa,NaN,Adoption,Spayed Female
16,8 months,A673952,Cat,Domestic Shorthair Mix,Brown Tabby/White,2013-07-05T00:00:00,2014-03-06T14:29:00,2014-03-06T14:29:00,NaN,SCRP,Transfer,Unknown
17,5 months,A686497,Cat,Domestic Shorthair Mix,Black Tabby,2014-03-22T00:00:00,2014-08-31T15:45:00,2014-08-31T15:45:00,Chester,NaN,Adoption,Neutered Male
18,1 year,A668547,Cat,Domestic Medium Hair Mix,Black/White,2012-12-04T00:00:00,2013-12-16T13:59:00,2013-12-16T13:59:00,*Preston,Partner,Transfer,Neutered Male
19,4 months,A669621,Dog,Plott Hound Mix,Brown Brindle/Black,2013-08-23T00:00:00,2013-12-25T09:47:00,2013-12-25T09:47:00,NaN,Partner,Transfer,Intact Female
20,2 months,A667311,Dog,Labrador Retriever Mix,Yellow,2013-09-01T00:00:00,2013-11-19T18:30:00,2013-11-19T18:30:00,Promise,NaN,Adoption,Spayed Female
21,2 months,A682393,Cat,Siamese,Seal Point,2014-04-27T00:00:00,2014-07-03T12:12:00,2014-07-03T12:12:00,*Bumble,Partner,Transfer,Intact Female
22,2 weeks,A681039,Cat,Domestic Shorthair Mix,Black,2014-05-27T00:00:00,2014-06-11T17:11:00,2014-06-11T17:11:00,NaN,Partner,Transfer,Unknown
23,2 months,A682532,Cat,Domestic Shorthair Mix,Torbie,2014-04-14T00:00:00,2014-07-03T17:01:00,2014-07-03T17:01:00,NaN,NaN,Adoption,Spayed Female
24,3 months,A669918,Dog,Labrador Retriever Mix,Tan/White,2013-09-30T00:00:00,2014-01-03T17:47:00,2014-01-03T17:47:00,NaN,NaN,Adoption,Spayed Female
25,3 months,A683779,Cat,Domestic Shorthair Mix,Black,2014-04-15T00:00:00,2014-07-19T17:36:00,2014-07-19T17:36:00,NaN,NaN,Adoption,Spayed Female
26,12 years,A678098,Dog,Labrador Retriever Mix,Black/White,2002-05-08T00:00:00,2014-07-09T11:54:00,2014-07-09T11:54:00,Shades,Foster,Adoption,Neutered Male
27,3 weeks,A686829,Cat,Domestic Shorthair Mix,Black,2014-08-05T00:00:00,2014-08-27T16:27:00,2014-08-27T16:27:00,NaN,Partner,Transfer,Intact Male
28,2 years,A677038,Dog,Chihuahua Shorthair Mix,Buff,2012-04-22T00:00:00,2014-04-26T13:00:00,2014-04-26T13:00:00,*Penny,NaN,Adoption,Spayed Female
29,4 years,A665344,Dog,Chihuahua Shorthair Mix,Red/White,2009-10-16T00:00:00,2013-11-02T17:47:00,2013-11-02T17:47:00,Ginger,NaN,Adoption,Spayed Female

In [29]:
## Verifying `age_group` populates sensibly

In [30]:
silver_outcomes[["age_upon_outcome", "age_group"]].value_counts().reset_index(name="count")

   age_upon_outcome age_group  count
0            1 year     Young  12664
1           2 years     Young  10824
2          2 months    Kitten   5977
3           3 years     Adult   5060
4          2 months     Puppy   3352
5           4 years     Adult   3017
6           5 years     Adult   2753
7          3 months    Kitten   2449
8           1 month    Kitten   2028
9           6 years     Adult   1870
10          8 years    Senior   1601
11          7 years     Adult   1582
12          3 weeks    Kitten   1372
13          1 month     Puppy   1365
14         4 months    Kitten   1365
15         10 years    Senior   1202
16          2 weeks    Kitten   1180
17         4 months     Puppy   1052
18         5 months     Puppy   1050
19         3 months     Puppy    990
20         6 months     Puppy    970
21        10 months     Puppy    959
22          9 years    Senior    853
23         8 months     Puppy    849
24          4 weeks    Kitten    747
25         5 months    Kitten    735
26         6 months    Kitten    638
27         7 months     Puppy    628
28         12 years    Senior    618
29         9 months     Puppy    516
30         11 years    Senior    447
31          1 weeks    Kitten    416
32        11 months     Puppy    408
33         13 years    Senior    402
34           1 week    Kitten    376
35         7 months    Kitten    343
36         8 months    Kitten    340
37        10 months    Kitten    268
38         14 years    Senior    260
39           3 days    Kitten    219
40         15 years    Senior    215
41         9 months    Kitten    175
42           2 days    Kitten    157
43          4 weeks     Puppy    154
44           4 days    Kitten    125
45          2 weeks     Puppy    121
46           6 days    Kitten    113
47         16 years    Senior    107
48            1 day    Kitten    106
49        11 months    Kitten    105
50          1 weeks     Puppy     88
51          3 weeks     Puppy     84
52           5 days    Kitten     80
53           2 days     Puppy     60
54         17 years    Senior     59
55          5 weeks    Kitten     50
56          0 years    Kitten     50
57           1 week     Puppy     46
58           6 days     Puppy     34
59            1 day     Puppy     34
60          0 years     Puppy     30
61         18 years    Senior     27
62           5 days     Puppy     22
63          5 weeks     Puppy     16
64           3 days     Puppy     15
65         19 years    Senior     13
66         20 years    Senior     12
67           4 days     Puppy      9
68         22 years    Senior      4

In [31]:
silver_outcomes[(silver_outcomes["animal_type"].isin(["Dog", "Cat"])) & (silver_outcomes["age_group"].isnull())].shape[0]

6

## Verifying deduplication

In [32]:
silver_outcomes.duplicated().sum()

0

## Investigating Intake/Outcome Count Mismatch

In [33]:
# Count intakes per animal
intake_counts = silver_intakes.groupby("animal_id").size().rename("n_intakes")

# Count outcomes per animal
outcome_counts = silver_outcomes.groupby("animal_id").size().rename("n_outcomes")

# Combine into one table
counts = pd.concat([intake_counts, outcome_counts], axis=1).fillna(0)

# How many animals have mismatched counts?
mismatched = counts[counts["n_intakes"] != counts["n_outcomes"]]
print(f"Animals with mismatched intake/outcome counts: {len(mismatched)}")
print(f"Total animals: {len(counts)}")
print(f"Percentage mismatched: {len(mismatched) / len(counts) * 100:.1f}%")

Animals with mismatched intake/outcome counts: 1543
Total animals: 73269
Percentage mismatched: 2.1%

In [34]:
# See the breakdown of how counts differ
counts["difference"] = counts["n_intakes"] - counts["n_outcomes"]
print(counts["difference"].value_counts().sort_index())

difference
-1.0     1021
 0.0    71726
 1.0      522
Name: count, dtype: int64

In [35]:
clean = counts[(counts["n_intakes"] == 1) & (counts["n_outcomes"] == 1)]
print(f"Animals with exactly 1 intake and 1 outcome: {len(clean)} ({len(clean)/len(counts)*100:.1f}%)")

Animals with exactly 1 intake and 1 outcome: 65743 (89.7%)

71,726 animals (98%) have matching intake and outcome counts and pair directly by chronological sequence. 522 animals have one unmatched intake (likely still in shelter at the dataset's end), and 1,021 have one unmatched outcome (likely intakes predating the dataset's 2013 start). All mismatches are off-by-one; unmatched events are excluded from stay-level metrics via an inner join, an assumption appropriate for aggregate analysis.