In [49]:
import duckdb
import pandas as pd

con = duckdb.connect("../data/shelterflow.duckdb")
bronze_intakes = con.execute("SELECT * FROM bronze_intakes").df()
bronze_outcomes = con.execute("SELECT * FROM bronze_outcomes").df()
silver_intakes = con.execute("SELECT * FROM silver_intakes").df()
silver_outcomes = con.execute("SELECT * FROM silver_outcomes").df()

pd.set_option("display.max_rows", None)

# `silver_intakes` Validation

In [50]:
silver_intakes.info()

<class 'pandas.DataFrame'>
RangeIndex: 80159 entries, 0 to 80158
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   animal_id           80159 non-null  str
 1   animal_type         80159 non-null  str
 2   intake_type         80159 non-null  str
 3   intake_condition    80159 non-null  str
 4   sex_upon_intake     80158 non-null  str
 5   age_upon_intake     80159 non-null  str
 6   found_location      80159 non-null  str
 7   color               80159 non-null  str
 8   name                55585 non-null  str
 9   breed               80159 non-null  str
 10  breed_standardized  80159 non-null  str
 11  age_in_days         80159 non-null  int32
 12  age_group           75379 non-null  str
 13  intake_date         80159 non-null  datetime64[us]
dtypes: datetime64[us](1), int32(1), str(12)
memory usage: 8.3 MB

## Comparing `silver_intakes` against `bronze_intakes`

In [51]:
silver_intakes.head(30)

,animal_id,animal_type,intake_type,intake_condition,sex_upon_intake,age_upon_intake,found_location,color,name,breed,breed_standardized,age_in_days,age_group,intake_date
0,A721791,Dog,Stray,Normal,Intact Male,2 months,12928 Ceder in Travis (TX),Brown Merle,NaN,Dachshund/Chihuahua Shorthair,Dachshund Mix,60,Puppy,2016-03-04
1,A676116,Cat,Stray,Normal,Intact Female,1 year,Hunnington Meadows in Austin (TX),Brown Tabby/White,*Girly,Domestic Shorthair Mix,Domestic Shorthair Mix,365,Young,2014-04-04
2,A694335,Cat,Stray,Injured,Intact Male,2 months,6900 Geneva in Austin (TX),Black/White,NaN,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2014-12-26
3,A751945,Cat,Stray,Normal,Intact Male,1 month,14704 Alps Drive in Travis (TX),Brown Tabby,*Harrier,Domestic Shorthair Mix,Domestic Shorthair Mix,30,Kitten,2017-06-15
4,A689627,Dog,Stray,Normal,Neutered Male,10 years,3755 B S Cap Texas Hwy in Austin (TX),Tan,*Jeb,Labrador Retriever Mix,Labrador Retriever Mix,3650,Senior,2014-10-07
5,A670075,Cat,Owner Surrender,Normal,Spayed Female,6 years,1101 E Parmer Ln #207 in Travis (TX),Brown Tabby,Cat,Maine Coon Mix,Maine Coon Mix,2190,Adult,2014-01-01
6,A686117,Dog,Stray,Normal,Intact Male,6 years,908 N Bend Dr in Austin (TX),White/Tan,Bonbon,Toy Poodle Mix,Toy Poodle Mix,2190,Adult,2016-10-03
7,A742459,Dog,Stray,Normal,Intact Male,4 weeks,9100 Fm 812 Road in Travis (TX),Black/White,Khan,Pit Bull Mix,Pit Bull Mix,28,Puppy,2017-01-22
8,A684113,Dog,Stray,Normal,Intact Female,1 year,1107 Lambie in Austin (TX),White,Sam,German Shepherd Mix,German Shepherd Mix,365,Young,2014-07-19
9,A746133,Cat,Stray,Normal,Intact Male,3 years,505 East Huntland Drive in Austin (TX),Black,NaN,Domestic Shorthair Mix,Domestic Shorthair Mix,1095,Adult,2017-03-29
10,A697282,Dog,Owner Surrender,Normal,Neutered Male,5 years,Austin (TX),Black/White,Dez,Labrador Retriever Mix,Labrador Retriever Mix,1825,Adult,2015-03-13
11,A678802,Cat,Stray,Normal,Intact Female,2 months,4700 East Riverside Dr in Austin (TX),Brown Tabby,Peepsqueak,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2014-05-12
12,A723672,Cat,Stray,Normal,Intact Male,3 weeks,1407 Warrior in Travis (TX),Orange Tabby,NaN,Domestic Shorthair Mix,Domestic Shorthair Mix,21,Kitten,2016-04-04
13,A644165,Dog,Owner Surrender,Normal,Neutered Male,4 years,11039 Maha Loop in Travis (TX),Brown/Black,Killer,German Shepherd Mix,German Shepherd Mix,1460,Adult,2014-12-22
14,A717196,Cat,Stray,Normal,Spayed Female,7 months,1881 Grove Blvd in Austin (TX),Calico,NaN,Domestic Shorthair Mix,Domestic Shorthair Mix,210,Kitten,2015-12-10
15,A515605,Dog,Stray,Normal,Spayed Female,6 years,Bennet Ave in Austin (TX),White/Black,Luna,Dogo Argentino Mix,Dogo Argentino Mix,2190,Adult,2014-02-13
16,A744618,Dog,Stray,Normal,Intact Female,2 years,45Th St And Guadalupe St in Austin (TX),White/Red,*Sophie,Labrador Retriever Mix,Labrador Retriever Mix,730,Young,2017-03-04
17,A728317,Cat,Owner Surrender,Normal,Neutered Male,2 years,Austin (TX),Brown Tabby,Cesar,Domestic Shorthair Mix,Domestic Shorthair Mix,730,Young,2016-06-02
18,A666467,Cat,Stray,Sick,Intact Female,2 months,7100 N 35 in Austin (TX),Orange Tabby/White,Gracie,Domestic Shorthair,Domestic Shorthair,60,Kitten,2013-11-01
19,A667299,Cat,Stray,Injured,Unknown,1 year,7Th/Pleasant Valley in Austin (TX),Black/White,NaN,Domestic Shorthair Mix,Domestic Shorthair Mix,365,Young,2013-11-15
20,A731452,Dog,Stray,Normal,Intact Male,2 years,Schmidt Ln And Anderson Rd in Manor (TX),Tan,*Oscar,Labrador Retriever Mix,Labrador Retriever Mix,730,Young,2016-07-22
21,A745239,Dog,Owner Surrender,Normal,Intact Female,2 months,401 Tawny Dr in Austin (TX),Tan/Black,*Rowena,Bruss Griffon Mix,Bruss Griffon Mix,60,Puppy,2017-03-15
22,A750967,Cat,Stray,Normal,Intact Male,3 weeks,3227 E 5Th St in Austin (TX),Brown Tabby,*Lewis,Domestic Shorthair Mix,Domestic Shorthair Mix,21,Kitten,2017-06-02
23,A713928,Cat,Owner Surrender,Normal,Spayed Female,9 months,Austin (TX),Blue Tabby,Lilly,Domestic Shorthair Mix,Domestic Shorthair Mix,270,Kitten,2015-10-15
24,A710971,Dog,Owner Surrender,Normal,Intact Female,7 months,Pflugerville (TX),Buff,Juliette,Labrador Retriever Mix,Labrador Retriever Mix,210,Puppy,2015-08-31
25,A698276,Dog,Stray,Normal,Intact Male,8 months,4408 Glomar in Austin (TX),White/Brown,Chuy,Chihuahua Shorthair/Smooth Fox Terrier,Chihuahua Shorthair Mix,240,Puppy,2015-03-08
26,A700566,Cat,Stray,Normal,Intact Female,1 week,629 Dalton Ln in Austin (TX),Blue Tabby,*Lyric,Domestic Shorthair Mix,Domestic Shorthair Mix,7,Kitten,2015-04-16
27,A684717,Cat,Owner Surrender,Normal,Intact Male,1 year,Austin (TX),Black,Junies,Domestic Shorthair Mix,Domestic Shorthair Mix,365,Young,2014-07-27
28,A717721,Dog,Stray,Normal,Intact Female,1 year,7201 Levander Loop in Austin (TX),Brown/White,*Ariel,Pit Bull Mix,Pit Bull Mix,365,Young,2015-12-13
29,A738017,Cat,Owner Surrender,Normal,Intact Female,2 months,133327 Black Canyon Dr in Austin (TX),Brown Tabby/White,*Ariel,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2016-11-08

In [52]:
bronze_intakes.head(30)

,age_upon_intake,animal_id,animal_type,breed,color,datetime,datetime2,found_location,intake_condition,intake_type,name,sex_upon_intake
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,Belle,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,Runster,Intact Male
2,4 weeks,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T07:59:00.000,Austin (TX),Sick,Stray,NaN,Intact Female
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,Rio,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,Odin,Neutered Male
5,2 years,A708452,Dog,Labrador Retriever Mix,Black/White,2015-07-30T14:37:00.000,2015-07-30T14:37:00.000,Austin (TX),Normal,Public Assist,Mumble,Intact Male
6,5 months,A731435,Cat,Domestic Shorthair Mix,Cream Tabby,2016-08-08T17:52:00.000,2016-08-08T17:52:00.000,Austin (TX),Normal,Owner Surrender,*Casey,Neutered Male
7,2 years,A760053,Dog,Chihuahua Shorthair,White/Tan,2017-10-11T15:46:00.000,2017-10-11T15:46:00.000,8800 South First Street in Austin (TX),Normal,Stray,NaN,Intact Male
8,5 months,A707375,Dog,Pit Bull,Brown/White,2015-07-11T18:19:00.000,2015-07-11T18:19:00.000,Galilee Court And Damita Jo Dr in Manor (TX),Normal,Stray,*Candy Cane,Intact Female
9,2 years,A696408,Dog,Chihuahua Shorthair,Tricolor,2015-02-04T12:58:00.000,2015-02-04T12:58:00.000,9705 Thaxton in Austin (TX),Normal,Stray,*Pearl,Intact Female
10,2 years,A743114,Cat,Domestic Shorthair Mix,Black/White,2017-02-04T10:10:00.000,2017-02-04T10:10:00.000,208 Beaver St in Austin (TX),Injured,Stray,NaN,Intact Female
11,14 years,A657188,Cat,Domestic Shorthair Mix,Brown Tabby/White,2013-11-10T17:19:00.000,2013-11-10T17:19:00.000,Austin (TX),Normal,Owner Surrender,Tommy,Neutered Male
12,4 weeks,A707658,Cat,Domestic Shorthair Mix,Black/White,2015-07-15T17:43:00.000,2015-07-15T17:43:00.000,6118 Fairway in Austin (TX),Normal,Stray,*Mint,Intact Female
13,1 month,A736287,Cat,Domestic Shorthair Mix,Torbie,2016-10-08T11:53:00.000,2016-10-08T11:53:00.000,South First And Stassney in Austin (TX),Normal,Stray,*Twilight,Intact Female
14,2 months,A697950,Dog,Australian Cattle Dog/Labrador Retriever,Tan/White,2015-03-04T11:22:00.000,2015-03-04T11:22:00.000,1501 S Fm 973 in Austin (TX),Normal,Stray,NaN,Intact Female
15,18 years,A298074,Dog,Parson Russell Terrier Mix,Black/White,2015-09-06T14:21:00.000,2015-09-06T14:21:00.000,1801 Westridge in Austin (TX),Normal,Stray,Stumpy,Spayed Female
16,2 years,A707974,Cat,Domestic Shorthair Mix,Blue,2015-07-20T18:13:00.000,2015-07-20T18:13:00.000,2307 Ventura in Austin (TX),Normal,Stray,*Cleopatra,Intact Female
17,5 months,A682230,Dog,Maltese Mix,White,2014-06-25T16:27:00.000,2014-06-25T16:27:00.000,3737 Keats Dr in Austin (TX),Normal,Stray,NaN,Intact Female
18,4 months,A749436,Dog,Dachshund Mix,Brown/White,2017-05-15T09:50:00.000,2017-05-15T09:50:00.000,East Pleasant Valley And Stassney in Austin (TX),Normal,Stray,NaN,Intact Male
19,1 year,A722979,Other,Bat Mix,Brown,2016-03-24T16:39:00.000,2016-03-24T16:39:00.000,4100 Westbank Dr in Austin (TX),Normal,Wildlife,NaN,Unknown
20,2 years,A696205,Cat,Domestic Shorthair Mix,Black,2015-02-12T11:57:00.000,2015-02-12T11:57:00.000,Austin (TX),Normal,Owner Surrender,Roo,Spayed Female
21,1 month,A759935,Dog,Labrador Retriever Mix,Black,2017-10-09T22:39:00.000,2017-10-09T22:39:00.000,4800 Cottonwood St in Austin (TX),Normal,Stray,Dieve,Intact Female
22,1 year,A666877,Dog,Dachshund Mix,Tan/White,2013-11-08T15:24:00.000,2013-11-08T15:24:00.000,Guadalupe/St. Johns in Austin (TX),Normal,Stray,*Romeo,Intact Male
23,4 days,A706507,Cat,Domestic Shorthair Mix,Black,2015-06-29T17:04:00.000,2015-06-29T17:04:00.000,5306 Peppertree in Austin (TX),Normal,Stray,NaN,Unknown
24,2 months,A732903,Dog,Labrador Retriever Mix,Black/White,2016-08-14T15:02:00.000,2016-08-14T15:02:00.000,Austin (TX),Injured,Stray,*Raven,Intact Female
25,1 day,A749400,Cat,Domestic Shorthair Mix,Blue,2017-05-14T14:19:00.000,2017-05-14T14:19:00.000,1834 Ferguson in Austin (TX),Normal,Stray,*Pepper,Intact Female
26,2 years,A727838,Cat,Domestic Shorthair Mix,Black,2016-05-26T14:01:00.000,2016-05-26T14:01:00.000,2504 Huntwick Dr in Austin (TX),Normal,Stray,NaN,Intact Female
27,2 weeks,A701811,Cat,Domestic Shorthair Mix,Gray Tabby,2015-05-05T07:29:00.000,2015-05-05T07:29:00.000,4434 Frontier Trl in Austin (TX),Nursing,Stray,NaN,Unknown
28,3 years,A700396,Dog,Pit Bull Mix,Black/White,2015-12-07T09:11:00.000,2015-12-07T09:11:00.000,4200 Smith School Rd in Austin (TX),Normal,Stray,Calseta,Spayed Female
29,4 years,A724378,Dog,Tibetan Spaniel Mix,Black/White,2016-04-16T13:36:00.000,2016-04-16T13:36:00.000,Austin (TX),Normal,Owner Surrender,Boxer,Intact Male

## Verifying `age_group` populates sensibly

In [53]:
silver_intakes[["age_upon_intake", "age_group"]].value_counts().reset_index(name="count")

   age_upon_intake age_group  count
0           1 year     Young  12433
1          2 years     Young  10762
2          3 years     Adult   4983
3          1 month    Kitten   4962
4          4 years     Adult   3025
5          5 years     Adult   2720
6          1 month     Puppy   2468
7          4 weeks    Kitten   2210
8          3 weeks    Kitten   2128
9         2 months    Kitten   2066
10        2 months     Puppy   1915
11         6 years     Adult   1862
12         7 years     Adult   1590
13         8 years    Senior   1535
14         2 weeks    Kitten   1433
15        10 years    Senior   1171
16        4 months     Puppy   1138
17        5 months     Puppy   1095
18        3 months    Kitten   1032
19        9 months     Puppy    913
20         9 years    Senior    876
21        3 months     Puppy    870
22        4 months    Kitten    864
23        6 months     Puppy    829
24        7 months     Puppy    807
25        8 months     Puppy    638
26        5 months    Kitten    606
27        12 years    Senior    594
28       10 months     Puppy    549
29          1 week    Kitten    519
30        6 months    Kitten    488
31        11 years    Senior    454
32       11 months     Puppy    448
33         1 weeks    Kitten    432
34        13 years    Senior    379
35        7 months    Kitten    318
36         4 weeks     Puppy    301
37          3 days    Kitten    286
38        9 months    Kitten    257
39        14 years    Senior    250
40        8 months    Kitten    240
41        15 years    Senior    213
42         0 years    Kitten    212
43          2 days    Kitten    212
44           1 day    Kitten    207
45         0 years     Puppy    202
46       10 months    Kitten    155
47          6 days    Kitten    148
48          1 week     Puppy    144
49         3 weeks     Puppy    143
50         5 weeks    Kitten    139
51           1 day     Puppy    129
52         2 weeks     Puppy    115
53          4 days    Kitten    112
54        16 years    Senior    108
55          3 days     Puppy     83
56          5 days    Kitten     82
57         1 weeks     Puppy     79
58          4 days     Puppy     72
59       11 months    Kitten     71
60         5 weeks     Puppy     64
61        17 years    Senior     59
62          2 days     Puppy     58
63          5 days     Puppy     36
64          6 days     Puppy     35
65        18 years    Senior     26
66        19 years    Senior     13
67        20 years    Senior     12
68        22 years    Senior      4

In [54]:
silver_intakes[(silver_intakes["animal_type"].isin(["Dog", "Cat"])) & (silver_intakes["age_group"].isnull())].shape[0]

0

## Verifying deduplication

In [55]:
silver_intakes.duplicated().sum()

0

# `silver_outcomes` Validation

In [56]:
silver_outcomes.info()

<class 'pandas.DataFrame'>
RangeIndex: 80658 entries, 0 to 80657
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   animal_id           80658 non-null  str
 1   animal_type         80658 non-null  str
 2   outcome_type        80644 non-null  str
 3   outcome_subtype     36886 non-null  str
 4   sex_upon_outcome    80656 non-null  str
 5   age_upon_outcome    80650 non-null  str
 6   name                56101 non-null  str
 7   color               80658 non-null  str
 8   breed               80658 non-null  str
 9   breed_standardized  80658 non-null  str
 10  age_in_days         80650 non-null  Int32
 11  age_group           75856 non-null  str
 12  outcome_date        80658 non-null  datetime64[us]
 13  date_of_birth       80658 non-null  datetime64[us]
dtypes: Int32(1), datetime64[us](2), str(11)
memory usage: 8.4 MB

In [57]:
silver_outcomes.head(30)

,animal_id,animal_type,outcome_type,outcome_subtype,sex_upon_outcome,age_upon_outcome,name,color,breed,breed_standardized,age_in_days,age_group,outcome_date,date_of_birth
0,A677038,Dog,Adoption,NaN,Spayed Female,2 years,*Penny,Buff,Chihuahua Shorthair Mix,Chihuahua Shorthair Mix,730,Young,2014-04-26,2012-04-22
1,A683068,Other,Euthanasia,Rabies Risk,Unknown,1 year,NaN,Black/Brown,Bat,Bat,365,NaN,2014-07-07,2013-07-06
2,A667028,Cat,Adoption,NaN,Neutered Male,1 year,*Mike,Orange Tabby,Domestic Shorthair Mix,Domestic Shorthair Mix,365,Young,2013-11-30,2012-11-11
3,A684123,Dog,Adoption,NaN,Spayed Female,8 months,Ruby,Black/White,Border Collie Mix,Border Collie Mix,240,Puppy,2014-07-23,2013-11-19
4,A568980,Dog,Return to Owner,NaN,Spayed Female,9 years,Polly,Tan,Blue Lacy Mix,Blue Lacy Mix,3285,Senior,2013-10-17,2004-03-19
5,A663004,Dog,Adoption,NaN,Spayed Female,8 months,*Allie,Black/White,Bulldog/Australian Cattle Dog,Bulldog Mix,240,Puppy,2013-10-02,2013-01-14
6,A683570,Dog,Adoption,NaN,Spayed Female,1 year,Layla,White,Boxer Mix,Boxer Mix,365,Young,2014-07-16,2013-07-12
7,A685756,Dog,Return to Owner,NaN,Spayed Female,1 year,Vivian,Black/White,German Shepherd Mix,German Shepherd Mix,365,Young,2014-08-12,2013-08-12
8,A679999,Cat,Transfer,SCRP,Neutered Male,1 year,NaN,Orange Tabby/White,Domestic Medium Hair Mix,Domestic Medium Hair Mix,365,Young,2014-05-29,2013-05-28
9,A571229,Dog,Transfer,Partner,Neutered Male,7 years,Chokolate,Brown Brindle,Pit Bull Mix,Pit Bull Mix,2555,Adult,2014-03-27,2006-04-18
10,A664596,Dog,Adoption,NaN,Spayed Female,5 months,Ellie,White,Great Pyrenees Mix,Great Pyrenees Mix,150,Puppy,2013-10-09,2013-05-06
11,A675129,Dog,Transfer,Partner,Spayed Female,2 years,NaN,White/Tricolor,Boxer Mix,Boxer Mix,730,Young,2014-03-27,2012-03-23
12,A686020,Dog,Return to Owner,NaN,Intact Female,8 months,Sadie,Black/Brown,German Shepherd Mix,German Shepherd Mix,240,Puppy,2014-08-16,2013-11-16
13,A682192,Dog,Transfer,Partner,Spayed Female,3 years,NaN,Black/White,German Shepherd Mix,German Shepherd Mix,1095,Adult,2014-07-01,2011-06-25
14,A652261,Dog,Return to Owner,NaN,Spayed Female,10 months,Puffy,Cream/White,Siberian Husky,Siberian Husky,300,Puppy,2013-11-24,2013-01-22
15,A668535,Dog,Adoption,NaN,Neutered Male,1 year,Beau,Black/Tan,Miniature Pinscher Mix,Miniature Pinscher Mix,365,Young,2013-12-08,2012-12-04
16,A674726,Cat,Return to Owner,NaN,Neutered Male,5 years,Mittens,Blue/White,Domestic Shorthair Mix,Domestic Shorthair Mix,1825,Adult,2014-03-25,2009-03-17
17,A687017,Cat,Transfer,SCRP,Intact Female,4 months,NaN,Orange Tabby/White,Domestic Shorthair Mix,Domestic Shorthair Mix,120,Kitten,2014-08-31,2014-04-15
18,A665084,Cat,Transfer,SCRP,Intact Female,7 months,NaN,Tortie,Domestic Shorthair Mix,Domestic Shorthair Mix,210,Kitten,2013-10-14,2013-02-13
19,A659515,Dog,Return to Owner,NaN,Neutered Male,14 years,Tango,Red,Vizsla,Vizsla,5110,Senior,2014-02-12,1999-07-26
20,A673425,Other,Euthanasia,Rabies Risk,Unknown,2 years,NaN,Gray/Black,Raccoon Mix,Raccoon Mix,730,NaN,2014-02-28,2012-02-24
21,A683415,Cat,Adoption,NaN,Neutered Male,2 months,Socks,Blue Tabby/White,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2014-07-16,2014-04-18
22,A670007,Cat,Transfer,SCRP,Spayed Female,2 years,NaN,Calico,Domestic Shorthair Mix,Domestic Shorthair Mix,730,Young,2014-01-02,2011-12-31
23,A674925,Dog,Adoption,NaN,Spayed Female,10 months,*Nelly,Tan/White,Jack Russell Terrier Mix,Jack Russell Terrier Mix,300,Puppy,2014-06-16,2013-07-20
24,A676309,Dog,Transfer,Partner,Intact Male,7 years,Snickers,Brown,Labrador Retriever Mix,Labrador Retriever Mix,2555,Adult,2014-04-18,2007-04-07
25,A662761,Cat,Adoption,NaN,Spayed Female,2 months,Petunia,Brown Tabby/White,Domestic Shorthair Mix,Domestic Shorthair Mix,60,Kitten,2013-10-28,2013-08-17
26,A495792,Cat,Adoption,NaN,Neutered Male,6 years,Macintosh,White/Brown Tabby,Domestic Shorthair Mix,Domestic Shorthair Mix,2190,Adult,2014-08-23,2007-10-13
27,A668670,Other,Euthanasia,Rabies Risk,Unknown,1 year,NaN,Gray/Black,Raccoon Mix,Raccoon Mix,365,NaN,2013-12-06,2012-12-06
28,A667339,Dog,Return to Owner,NaN,Neutered Male,3 years,Maximus,Blue/Tan,Doberman Pinsch Mix,Doberman Pinsch Mix,1095,Adult,2013-12-21,2010-12-19
29,A668221,Dog,Transfer,Partner,Neutered Male,2 years,*Scrappy,Tricolor,Rat Terrier Mix,Rat Terrier Mix,730,Young,2013-12-20,2011-11-30

In [58]:
bronze_outcomes.head(30)

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,A684346,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-07T00:00:00,2014-07-22T16:04:00,2014-07-22T16:04:00,NaN,Partner,Transfer,Intact Male
1,1 year,A666430,Dog,Beagle Mix,White/Brown,2012-11-06T00:00:00,2013-11-07T11:47:00,2013-11-07T11:47:00,Lucy,Partner,Transfer,Spayed Female
2,1 year,A675708,Dog,Pit Bull,Blue/White,2013-03-31T00:00:00,2014-06-03T14:20:00,2014-06-03T14:20:00,*Johnny,NaN,Adoption,Neutered Male
3,9 years,A680386,Dog,Miniature Schnauzer Mix,White,2005-06-02T00:00:00,2014-06-15T15:50:00,2014-06-15T15:50:00,Monday,Partner,Transfer,Neutered Male
4,5 months,A683115,Other,Bat Mix,Brown,2014-01-07T00:00:00,2014-07-07T14:04:00,2014-07-07T14:04:00,NaN,Rabies Risk,Euthanasia,Unknown
5,4 months,A664462,Dog,Leonberger Mix,Brown/White,2013-06-03T00:00:00,2013-10-07T13:06:00,2013-10-07T13:06:00,*Edgar,Partner,Transfer,Intact Male
6,1 month,A685067,Cat,Domestic Shorthair Mix,Blue Tabby/White,2014-06-16T00:00:00,2014-08-14T18:45:00,2014-08-14T18:45:00,Lucy,NaN,Adoption,Intact Female
7,3 months,A678580,Cat,Domestic Shorthair Mix,White/Black,2014-03-26T00:00:00,2014-06-29T17:45:00,2014-06-29T17:45:00,*Frida,Offsite,Adoption,Spayed Female
8,1 year,A675405,Cat,Domestic Medium Hair Mix,Black/White,2013-03-27T00:00:00,2014-03-28T14:55:00,2014-03-28T14:55:00,Stella Luna,NaN,Return to Owner,Spayed Female
9,2 years,A673652,Dog,Papillon/Border Collie,Black/White,2012-02-28T00:00:00,2014-03-28T14:39:00,2014-03-28T14:39:00,Fancy,Partner,Transfer,Neutered Male
10,2 months,A677679,Dog,Chihuahua Shorthair/Pomeranian,Black,2014-03-07T00:00:00,2014-05-26T19:10:00,2014-05-26T19:10:00,Kash,Foster,Adoption,Neutered Male
11,4 years,A640655,Dog,Miniature Schnauzer/Miniature Poodle,White,2009-04-27T00:00:00,2014-04-25T11:17:00,2014-04-25T11:17:00,Sandy,NaN,Return to Owner,Spayed Female
12,2 years,A680396,Dog,Rat Terrier Mix,White/Black,2012-06-02T00:00:00,2014-06-15T15:11:00,2014-06-15T15:11:00,*Truman,Partner,Transfer,Neutered Male
13,1 year,A674298,Dog,Pit Bull Mix,Brown Brindle/White,2013-03-11T00:00:00,2014-04-16T12:51:00,2014-04-16T12:51:00,*Newt,Partner,Transfer,Neutered Male
14,3 weeks,A670420,Cat,Domestic Shorthair Mix,Black/White,2013-12-16T00:00:00,2014-01-09T19:29:00,2014-01-09T19:29:00,NaN,Partner,Transfer,Intact Male
15,2 months,A684460,Cat,Domestic Shorthair Mix,Brown Tabby,2014-06-02T00:00:00,2014-08-13T15:04:00,2014-08-13T15:04:00,Elsa,NaN,Adoption,Spayed Female
16,8 months,A673952,Cat,Domestic Shorthair Mix,Brown Tabby/White,2013-07-05T00:00:00,2014-03-06T14:29:00,2014-03-06T14:29:00,NaN,SCRP,Transfer,Unknown
17,5 months,A686497,Cat,Domestic Shorthair Mix,Black Tabby,2014-03-22T00:00:00,2014-08-31T15:45:00,2014-08-31T15:45:00,Chester,NaN,Adoption,Neutered Male
18,1 year,A668547,Cat,Domestic Medium Hair Mix,Black/White,2012-12-04T00:00:00,2013-12-16T13:59:00,2013-12-16T13:59:00,*Preston,Partner,Transfer,Neutered Male
19,4 months,A669621,Dog,Plott Hound Mix,Brown Brindle/Black,2013-08-23T00:00:00,2013-12-25T09:47:00,2013-12-25T09:47:00,NaN,Partner,Transfer,Intact Female
20,2 months,A667311,Dog,Labrador Retriever Mix,Yellow,2013-09-01T00:00:00,2013-11-19T18:30:00,2013-11-19T18:30:00,Promise,NaN,Adoption,Spayed Female
21,2 months,A682393,Cat,Siamese,Seal Point,2014-04-27T00:00:00,2014-07-03T12:12:00,2014-07-03T12:12:00,*Bumble,Partner,Transfer,Intact Female
22,2 weeks,A681039,Cat,Domestic Shorthair Mix,Black,2014-05-27T00:00:00,2014-06-11T17:11:00,2014-06-11T17:11:00,NaN,Partner,Transfer,Unknown
23,2 months,A682532,Cat,Domestic Shorthair Mix,Torbie,2014-04-14T00:00:00,2014-07-03T17:01:00,2014-07-03T17:01:00,NaN,NaN,Adoption,Spayed Female
24,3 months,A669918,Dog,Labrador Retriever Mix,Tan/White,2013-09-30T00:00:00,2014-01-03T17:47:00,2014-01-03T17:47:00,NaN,NaN,Adoption,Spayed Female
25,3 months,A683779,Cat,Domestic Shorthair Mix,Black,2014-04-15T00:00:00,2014-07-19T17:36:00,2014-07-19T17:36:00,NaN,NaN,Adoption,Spayed Female
26,12 years,A678098,Dog,Labrador Retriever Mix,Black/White,2002-05-08T00:00:00,2014-07-09T11:54:00,2014-07-09T11:54:00,Shades,Foster,Adoption,Neutered Male
27,3 weeks,A686829,Cat,Domestic Shorthair Mix,Black,2014-08-05T00:00:00,2014-08-27T16:27:00,2014-08-27T16:27:00,NaN,Partner,Transfer,Intact Male
28,2 years,A677038,Dog,Chihuahua Shorthair Mix,Buff,2012-04-22T00:00:00,2014-04-26T13:00:00,2014-04-26T13:00:00,*Penny,NaN,Adoption,Spayed Female
29,4 years,A665344,Dog,Chihuahua Shorthair Mix,Red/White,2009-10-16T00:00:00,2013-11-02T17:47:00,2013-11-02T17:47:00,Ginger,NaN,Adoption,Spayed Female

In [59]:
## Verifying `age_group` populates sensibly

In [60]:
silver_outcomes[["age_upon_outcome", "age_group"]].value_counts().reset_index(name="count")

   age_upon_outcome age_group  count
0            1 year     Young  12664
1           2 years     Young  10824
2          2 months    Kitten   5977
3           3 years     Adult   5060
4          2 months     Puppy   3352
5           4 years     Adult   3017
6           5 years     Adult   2753
7          3 months    Kitten   2449
8           1 month    Kitten   2028
9           6 years     Adult   1870
10          8 years    Senior   1601
11          7 years     Adult   1582
12          3 weeks    Kitten   1372
13         4 months    Kitten   1365
14          1 month     Puppy   1365
15         10 years    Senior   1202
16          2 weeks    Kitten   1180
17         4 months     Puppy   1052
18         5 months     Puppy   1050
19         3 months     Puppy    990
20         6 months     Puppy    970
21        10 months     Puppy    959
22          9 years    Senior    853
23         8 months     Puppy    849
24          4 weeks    Kitten    747
25         5 months    Kitten    735
26         6 months    Kitten    638
27         7 months     Puppy    628
28         12 years    Senior    618
29         9 months     Puppy    516
30         11 years    Senior    447
31          1 weeks    Kitten    416
32        11 months     Puppy    408
33         13 years    Senior    402
34           1 week    Kitten    376
35         7 months    Kitten    343
36         8 months    Kitten    340
37        10 months    Kitten    268
38         14 years    Senior    260
39           3 days    Kitten    219
40         15 years    Senior    215
41         9 months    Kitten    175
42           2 days    Kitten    157
43          4 weeks     Puppy    154
44           4 days    Kitten    125
45          2 weeks     Puppy    121
46           6 days    Kitten    113
47         16 years    Senior    107
48            1 day    Kitten    106
49        11 months    Kitten    105
50          1 weeks     Puppy     88
51          3 weeks     Puppy     84
52           5 days    Kitten     80
53           2 days     Puppy     60
54         17 years    Senior     59
55          5 weeks    Kitten     50
56          0 years    Kitten     50
57           1 week     Puppy     46
58           6 days     Puppy     34
59            1 day     Puppy     34
60          0 years     Puppy     30
61         18 years    Senior     27
62           5 days     Puppy     22
63          5 weeks     Puppy     16
64           3 days     Puppy     15
65         19 years    Senior     13
66         20 years    Senior     12
67           4 days     Puppy      9
68         22 years    Senior      4

In [61]:
silver_outcomes[(silver_outcomes["animal_type"].isin(["Dog", "Cat"])) & (silver_outcomes["age_group"].isnull())].shape[0]

6

## Verifying deduplication

In [62]:
silver_outcomes.duplicated().sum()

0